// Harness is disabled unless QA_RUN_KEY and a short QA_RUN_UNTIL are explicitly supplied for a controlled deployment.
import {createClient} from 'jsr:@supabase/supabase-js@2.57.4';
const QA_RUN_KEY='__QA_RUN_KEY__',QA_RUN_UNTIL=0;
Deno.serve(async req=>{
 if(req.method!=='POST'||Date.now()>QA_RUN_UNTIL||req.headers.get('x-qa-run')!==QA_RUN_KEY)return new Response('QA harness disabled',{status:410});
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,admin=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}}),stamp=crypto.randomUUID(),userIds:string[]=[],clientIds:string[]=[],results:string[]=[],objects:string[]=[];let orgId:string|null=null;
 const must=(value:unknown,label:string)=>{if(!value)throw Error(label);results.push(label);};
 const unwrap=(r:any)=>{if(r.error)throw r.error;return r.data;};
 async function identity(role:string){const password=crypto.randomUUID()+crypto.randomUUID(),email=`qa-${stamp}-${role}@example.invalid`;const user=unwrap(await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:'LEGAL EDGE QA '+role}})).user;userIds.push(user.id);let client=unwrap(await admin.from('clients').select('id').eq('profile_id',user.id).maybeSingle());if(!client){const profile=await admin.from('profiles').upsert({id:user.id,role:'client',full_name:'LEGAL EDGE QA '+role,email});if(profile.error)throw Error('QA profile: '+profile.error.message);client=unwrap(await admin.from('clients').insert({profile_id:user.id,display_name:'LEGAL EDGE QA '+role,status:'active'}).select('id').single());}clientIds.push(client.id);const api=createClient(url,anon,{auth:{persistSession:false}});const login=unwrap(await api.auth.signInWithPassword({email,password}));return {id:user.id,clientId:client.id,api,token:login.session.access_token};}
 let failure:string|null=null,cleanup:string[]=[];
 try{
 const coach=await identity('coach');unwrap(await admin.from('profiles').update({role:'coach'}).eq('id',coach.id));unwrap(await admin.from('clients').delete().eq('id',coach.clientId));
 orgId=unwrap(await coach.api.from('firm_organizations').insert({coach_id:coach.id,name:'LEGAL EDGE QA '+stamp,employee_count:20}).select('id').single()).id;
 const today=new Date().toISOString().slice(0,10),d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);const week=d.toISOString().slice(0,10),before=new Date(Date.now()-60000).toISOString();
 const pilot=unwrap(await coach.api.from('firm_pilots').insert({organization_id:orgId,coach_id:coach.id,name:'QA isolated pilot',capacity:10,status:'active',start_date:week,end_date:new Date(Date.now()+90*864e5).toISOString().slice(0,10),minimum_report_count:5}).select('id').single());
 const people=[];for(let i=0;i<6;i++){const person=await identity('person'+i);people.push(person);unwrap(await admin.from('clients').update({coach_id:coach.id,display_name:'QA participant'}).eq('id',person.clientId));const member=unwrap(await coach.api.from('firm_participants').insert({pilot_id:pilot.id,client_id:person.clientId,status:'active',joined_at:before}).select('id').single());unwrap(await person.api.from('firm_consents').insert({participant_id:member.id,client_id:person.clientId,include_weekly_ratings:true,accepted_at:before,statement_version:'QA ONLY'}));unwrap(await admin.from('checkins').insert({client_id:person.clientId,period_start:week,energy:7,sleep:8,stress:4,workload:6,training_adherence:75,nutrition_adherence:80,wins:'QA PRIVATE TEXT DO NOT EXPORT'}));}
 const employerPassword=crypto.randomUUID()+crypto.randomUUID(),employerEmail=`qa-${stamp}-employer@example.invalid`;const response=await fetch(url+'/functions/v1/provision-employer',{method:'POST',headers:{Authorization:'Bearer '+coach.token,apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({organization_id:orgId,email:employerEmail,password:employerPassword,full_name:'QA EMPLOYER'})});const created=await response.json();must(response.ok&&created.access?.id,'Assigned coach provisions employer through live function');const employerProfile=unwrap(await admin.from('profiles').select('id').eq('email',employerEmail).single());userIds.push(employerProfile.id);const employer=createClient(url,anon,{auth:{persistSession:false}});unwrap(await employer.auth.signInWithPassword({email:employerEmail,password:employerPassword}));
 const report=unwrap(await employer.rpc('employer_weekly_report',{target_pilot:pilot.id,target_week:week}));must(report.energy===7&&report.respondents===6,'Signed employer receives six-person group report');must(!JSON.stringify(report).includes('QA PRIVATE TEXT')&&!JSON.stringify(report).includes(people[0].clientId),'Employer report excludes private text and client identifiers');must(unwrap(await employer.from('checkins').select('id')).length===0,'Employer cannot query check-ins');must(unwrap(await employer.from('clients').select('id')).length===0,'Employer cannot query client roster');
 const outsider=await identity('outsider');must(Boolean((await outsider.api.rpc('employer_weekly_report',{target_pilot:pilot.id,target_week:week})).error),'Unassigned account cannot access employer report');must(Boolean((await people[0].api.from('profiles').update({role:'coach'}).eq('id',people[0].id)).error),'Client cannot escalate own profile role');
 const bytes=Uint8Array.from(atob('__AUDIO_BASE64__'),c=>c.charCodeAt(0)),owner=people[0],path=owner.clientId+'/qa-'+stamp+'.mp3';unwrap(await owner.api.storage.from('client-files').upload(path,bytes,{contentType:'audio/mpeg'}));objects.push(path);const audio=unwrap(await owner.api.from('client_files').insert({client_id:owner.clientId,uploaded_by:owner.id,file_type:'checkin_audio',storage_path:path,original_name:'qa.mp3',mime_type:'audio/mpeg',notes:'QA isolated private audio'}).select('id').single());
 must(unwrap(await owner.api.from('client_files').select('id').eq('id',audio.id)).length===1,'Signed client persists private audio record');const signed=unwrap(await owner.api.storage.from('client-files').createSignedUrl(path,60));must((await fetch(signed.signedUrl)).ok,'Signed owner plays stored audio');must((await coach.api.storage.from('client-files').createSignedUrl(path,60)).error===null,'Assigned coach can play client audio');must(Boolean((await people[1].api.storage.from('client-files').createSignedUrl(path,60)).error),'Other client cannot sign audio URL');must(Boolean((await employer.storage.from('client-files').createSignedUrl(path,60)).error),'Employer cannot sign audio URL');must(unwrap(await employer.from('client_files').select('id')).length===0,'Employer cannot query audio metadata');
 const token=[...crypto.getRandomValues(new Uint8Array(32))].map(b=>b.toString(16).padStart(2,'0')).join(''),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))].map(b=>b.toString(16).padStart(2,'0')).join('');const key=unwrap(await owner.api.from('client_health_ingest_keys').insert({client_id:owner.clientId,token_hash:hash,provider:'apple_health',scopes:['steps'],expires_at:new Date(Date.now()+864e5).toISOString()}).select('id').single());
 async function ingest(){return fetch(url+'/functions/v1/health-device-ingest',{method:'POST',headers:{'X-Legal-Edge-Key':token,'Content-Type':'application/json'},body:JSON.stringify({data:{metrics:[{name:'step_count',units:'count',data:[{date:today,qty:1234}]},{name:'body_mass',units:'kg',data:[{date:today,qty:80}]}]}})});}
 const upload=await ingest();must(upload.ok,'Authenticated device key writes through live ingest endpoint');const rows=unwrap(await owner.api.from('client_health_daily').select('*').eq('date',today));must(rows.length===1&&rows[0].steps===1234&&rows[0].weight_kg===null,'Ingest saves own steps and excludes unconsented weight');must((await ingest()).status===429,'Rapid duplicate uploads are rate limited');unwrap(await admin.from('client_health_ingest_keys').update({last_received_at:null}).eq('id',key.id));must((await ingest()).ok,'Daily snapshot can be resent');must(unwrap(await owner.api.from('client_health_daily').select('id').eq('date',today)).length===1,'Repeated daily snapshot does not double-count');must(unwrap(await outsider.api.from('client_health_ingest_keys').select('id')).length===0,'Other client cannot see device keys');must(Boolean((await outsider.api.from('client_health_ingest_keys').insert({client_id:owner.clientId,token_hash:'a'.repeat(64),provider:'apple_health',scopes:['steps'],expires_at:new Date(Date.now()+864e5).toISOString()})).error),'Other client cannot issue key for peer');unwrap(await owner.api.from('client_health_ingest_keys').update({revoked_at:new Date().toISOString()}).eq('id',key.id));must((await ingest()).status===401,'Revoked device key cannot upload');
 unwrap(await admin.from('firm_consents').delete().in('client_id',people.slice(0,2).map(p=>p.clientId)));const suppressed=unwrap(await employer.rpc('employer_weekly_report',{target_pilot:pilot.id,target_week:week}));must(suppressed.energy===null&&suppressed.respondents===null,'Under-five reports suppress scores and response counts after consent removal');
 }catch(e){failure=String((e as any)?.message||e);}
 finally{if(objects.length){const r=await admin.storage.from('client-files').remove(objects);if(r.error)cleanup.push('storage cleanup failed');}if(orgId){const pilots=await admin.from('firm_pilots').select('id').eq('organization_id',orgId);const ids=(pilots.data||[]).map(p=>p.id);if(ids.length){const members=await admin.from('firm_participants').select('id').in('pilot_id',ids);const mids=(members.data||[]).map(m=>m.id);if(mids.length)await admin.from('firm_consents').delete().in('participant_id',mids);await admin.from('firm_participants').delete().in('pilot_id',ids);await admin.from('firm_pilots').delete().in('id',ids);}const r=await admin.from('firm_organizations').delete().eq('id',orgId);if(r.error)cleanup.push('firm cleanup failed');}if(clientIds.length){const r=await admin.from('clients').delete().in('id',clientIds);if(r.error)cleanup.push('client cleanup failed');}for(const id of userIds){const r=await admin.auth.admin.deleteUser(id);if(r.error)cleanup.push('identity cleanup failed');}}
 return new Response(JSON.stringify({passed:results,failure,cleanup}),{status:failure||cleanup.length?500:200,headers:{'Content-Type':'application/json'}});
});
