// Exact movement aliases only: never substitute equipment or exercise variants.
const rpTechniqueDemos = [
 {id:'UCXxvVItLoM',seconds:18,name:'Seated cable row',aliases:['seated cable row'],cues:['Sit tall with feet supported and knees slightly bent.','Pull the handle towards your lower ribs, without rocking back.','Return slowly, letting your arms reach forward.']},
 {id:'HzIiNhHhhtA',seconds:13,name:'Seated dumbbell shoulder press',aliases:['seated dumbbell shoulder press','seated db shoulder press','seated dumbbell shoulder press (light)'],cues:['Sit against the backrest with feet planted.','Press the dumbbells overhead without arching your back.','Lower under control through your comfortable range.']},
 {id:'EUIri47Epcg',seconds:15,name:'Normal-grip lat pulldown',aliases:['lat pulldown','normal grip pulldown'],cues:['Secure your thighs under the pad and keep your torso steady.','Pull your elbows down, bringing the bar towards your upper chest.','Return slowly; avoid swinging or pulling behind your head.']},
 {id:'5CECBjd7HLQ',seconds:12,name:'Incline dumbbell press',aliases:['incline dumbbell press','incline dumbbell bench press','incline db press'],cues:['Set the bench to a moderate incline and plant both feet.','Lower the dumbbells under control beside your chest.','Press up with wrists stacked over your forearms.']},
 {"id":"m0FOpMEgero","seconds":null,"name":"Leg extension","group":"Legs","aliases":["leg extension"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"yZmx_Ac3880","seconds":null,"name":"Leg press","group":"Legs","aliases":["leg press","double-leg leg press"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"rYgNArpwE7E","seconds":null,"name":"Hack squat machine","group":"Legs","aliases":["hack squat machine","hack squat"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"i7J5h7BJ07g","seconds":null,"name":"High-bar squat","group":"Legs","aliases":["high bar squat","high-bar squat"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"HHxNbhP16UE","seconds":null,"name":"Front squat","group":"Legs","aliases":["front squat"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"L__-j2v_LPM","seconds":null,"name":"Belt squat","group":"Legs","aliases":["belt squat"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"Orxowest56U","seconds":null,"name":"Seated leg curl","group":"Legs","aliases":["seated leg curl","seated hamstring curl"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"n5WDXD_mpVY","seconds":null,"name":"Lying leg curl","group":"Legs","aliases":["lying leg curl"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"5_ejbGfdAQE","seconds":null,"name":"45-degree back raise","group":"Legs","aliases":["45 degree back raise","45-degree back raise"],"cues":["Adjust the setup to your body and plant your feet securely.","Use your prescribed range with a steady, controlled movement.","Return slowly; keep the same technique across every repetition."]},
 {"id":"YQ2s_Y7g5Qk","seconds":null,"name":"Flat dumbbell bench press","group":"Chest","aliases":["flat dumbbell bench press","db flat press","db bench press","dumbbell bench press"],"cues":["Set the bench or seat and keep your body supported.","Lower under control through the range agreed with your coach.","Press or bring your arms together without bouncing or swinging."]},
 {"id":"NwzUje3z0qY","seconds":null,"name":"Machine chest press","group":"Chest","aliases":["machine chest press","seated machine chest press"],"cues":["Set the bench or seat and keep your body supported.","Lower under control through the range agreed with your coach.","Press or bring your arms together without bouncing or swinging."]},
 {"id":"8urE8Z8AMQ4","seconds":null,"name":"Smith machine incline press","group":"Chest","aliases":["smith machine incline press"],"cues":["Set the bench or seat and keep your body supported.","Lower under control through the range agreed with your coach.","Press or bring your arms together without bouncing or swinging."]},
 {"id":"O5viuEPDXKY","seconds":null,"name":"Smith machine bench press","group":"Chest","aliases":["smith machine bench press"],"cues":["Set the bench or seat and keep your body supported.","Lower under control through the range agreed with your coach.","Press or bring your arms together without bouncing or swinging."]},
 {"id":"JFm8KbhjibM","seconds":null,"name":"Flat dumbbell fly","group":"Chest","aliases":["flat dumbbell fly","flat dumbbell flye"],"cues":["Set the bench or seat and keep your body supported.","Lower under control through the range agreed with your coach.","Press or bring your arms together without bouncing or swinging."]},
 {"id":"FDay9wFe5uE","seconds":null,"name":"Machine fly","group":"Chest","aliases":["machine fly","machine flye"],"cues":["Set the bench or seat and keep your body supported.","Lower under control through the range agreed with your coach.","Press or bring your arms together without bouncing or swinging."]},
 {"id":"O-OBCfyh9Fw","seconds":null,"name":"Pec deck fly","group":"Chest","aliases":["pec deck fly","pec deck flye"],"cues":["Set the bench or seat and keep your body supported.","Lower under control through the range agreed with your coach.","Press or bring your arms together without bouncing or swinging."]},
 {"id":"mm6_WcoCVTA","seconds":null,"name":"Push-up","group":"Chest","aliases":["push-up","push-ups","pushup","pushups"],"cues":["Set the bench or seat and keep your body supported.","Lower under control through the range agreed with your coach.","Press or bring your arms together without bouncing or swinging."]},
 {"id":"DMo3HJoawrU","seconds":null,"name":"Single-arm dumbbell row","group":"Back","aliases":["single arm dumbbell row","single-arm dumbbell row","1-arm db row"],"cues":["Secure your position and use the grip shown for this movement.","Pull with controlled elbows while keeping your torso steady.","Return slowly without jerking or using momentum."]},
 {"id":"_FrrYQxA6kc","seconds":null,"name":"Machine chest-supported row","group":"Back","aliases":["chest supported row machine","machine chest supported row"],"cues":["Secure your position and use the grip shown for this movement.","Pull with controlled elbows while keeping your torso steady.","Return slowly without jerking or using momentum."]},
 {"id":"tZUYS7X50so","seconds":null,"name":"Incline dumbbell row","group":"Back","aliases":["incline dumbbell row"],"cues":["Secure your position and use the grip shown for this movement.","Pull with controlled elbows while keeping your torso steady.","Return slowly without jerking or using momentum."]},
 {"id":"yPis7nlbqdY","seconds":null,"name":"Chest-supported T-bar row","group":"Back","aliases":["chest-supported t-bar row","chest supported t-bar row"],"cues":["Secure your position and use the grip shown for this movement.","Pull with controlled elbows while keeping your torso steady.","Return slowly without jerking or using momentum."]},
 {"id":"--utaPT7XYQ","seconds":null,"name":"Neutral-grip lat pulldown","group":"Back","aliases":["neutral-grip lat pulldown","neutral grip lat pulldown","parallel pulldown"],"cues":["Secure your position and use the grip shown for this movement.","Pull with controlled elbows while keeping your torso steady.","Return slowly without jerking or using momentum."]},
 {"id":"GRHLNfmr_oI","seconds":null,"name":"Narrow-grip lat pulldown","group":"Back","aliases":["close-grip lat pulldown","close grip lat pulldown","narrow grip pulldown"],"cues":["Secure your position and use the grip shown for this movement.","Pull with controlled elbows while keeping your torso steady.","Return slowly without jerking or using momentum."]},
 {"id":"iWpoegdfgtc","seconds":null,"name":"Normal-grip pull-up","group":"Back","aliases":["normal grip pullup","pull-ups","pull ups"],"cues":["Secure your position and use the grip shown for this movement.","Pull with controlled elbows while keeping your torso steady.","Return slowly without jerking or using momentum."]},
 {"id":"G9uNaXGTJ4w","seconds":null,"name":"Straight-arm pulldown","group":"Back","aliases":["straight arm pulldown","straight-arm pulldown"],"cues":["Secure your position and use the grip shown for this movement.","Pull with controlled elbows while keeping your torso steady.","Return slowly without jerking or using momentum."]},
 {"id":"OuG1smZTsQQ","seconds":null,"name":"Dumbbell lateral raise","group":"Shoulders","aliases":["dumbbell lateral raise","db lateral raise","lateral raises"],"cues":["Choose a controllable load and keep your torso steady.","Lift through the comfortable range prescribed by your coach.","Lower slowly without swinging or shrugging to move the load."]},
 {"id":"qr3ziolhjvQ","seconds":null,"name":"Cable face pull","group":"Shoulders","aliases":["cable face pull","face pull"],"cues":["Choose a controllable load and keep your torso steady.","Lift through the comfortable range prescribed by your coach.","Lower slowly without swinging or shrugging to move the load."]},
 {"id":"0o07iGKUarI","seconds":null,"name":"Machine lateral raise","group":"Shoulders","aliases":["machine lateral raise"],"cues":["Choose a controllable load and keep your torso steady.","Lift through the comfortable range prescribed by your coach.","Lower slowly without swinging or shrugging to move the load."]},
 {"id":"XOEL4MgekYE","seconds":null,"name":"Dumbbell hammer curl","group":"Arms","aliases":["dumbbell hammer curl","db hammer curl"],"cues":["Keep your upper arms steady and use the demonstrated grip.","Move at the elbow without swinging your torso.","Return slowly through the prescribed comfortable range."]},
 {"id":"aTYlqC_JacQ","seconds":null,"name":"Incline dumbbell curl","group":"Arms","aliases":["incline dumbbell curl","incline db curl"],"cues":["Keep your upper arms steady and use the demonstrated grip.","Move at the elbow without swinging your torso.","Return slowly through the prescribed comfortable range."]},
 {"id":"Ja6ZlIDONac","seconds":null,"name":"Machine preacher curl","group":"Arms","aliases":["machine preacher curl","preacher curl machine"],"cues":["Keep your upper arms steady and use the demonstrated grip.","Move at the elbow without swinging your torso.","Return slowly through the prescribed comfortable range."]},
 {"id":"6Fzep104f0s","seconds":null,"name":"Cable triceps pushdown","group":"Arms","aliases":["cable triceps pushdown","cable triceps pressdown","cable tricep pushdown"],"cues":["Keep your upper arms steady and use the demonstrated grip.","Move at the elbow without swinging your torso.","Return slowly through the prescribed comfortable range."]},
 {"id":"-xa-6cQaZKY","seconds":null,"name":"Rope triceps pushdown","group":"Arms","aliases":["rope triceps pushdown","tricep rope pushdown"],"cues":["Keep your upper arms steady and use the demonstrated grip.","Move at the elbow without swinging your torso.","Return slowly through the prescribed comfortable range."]},
 {"id":"1u18yJELsh0","seconds":null,"name":"Cable overhead triceps extension","group":"Arms","aliases":["cable overhead triceps extension"],"cues":["Keep your upper arms steady and use the demonstrated grip.","Move at the elbow without swinging your torso.","Return slowly through the prescribed comfortable range."]},
 {"id":"KxEYX_cuesM","seconds":null,"name":"Leg-press calf raise","group":"Calves","aliases":["leg press calves","leg-press calf raise"],"cues":["Place the balls of your feet securely on the platform.","Raise and lower your heels with control through the agreed range.","Pause briefly rather than bouncing through the repetitions."]},
 {"id":"N3awlEyTY98","seconds":null,"name":"Calf raise machine","group":"Calves","aliases":["calf raise machine"],"cues":["Place the balls of your feet securely on the platform.","Raise and lower your heels with control through the agreed range.","Pause briefly rather than bouncing through the repetitions."]},
 {"id":"__qfDhdByMY","seconds":null,"name":"Stair calf raise","group":"Calves","aliases":["stair calf raise"],"cues":["Place the balls of your feet securely on the platform.","Raise and lower your heels with control through the agreed range.","Pause briefly rather than bouncing through the repetitions."]}
];
function rpDemoForExercise(exercise){
 const name=String(exercise.name||'').trim().toLowerCase().replace(/\s+/g,' ');
 return rpTechniqueDemos.find(demo=>demo.aliases.includes(name))||null;
}
function rpDemoMarkup(demo){
 // Load only after opening: dozens of hidden players must not slow the planner.
 const url='https://www.youtube-nocookie.com/embed/'+demo.id+'?start=0&end=45&rel=0&playsinline=1';
 return `<section class="rp-demo"><details class="rp-video"><summary><span class="rp-play" aria-hidden="true">▶</span><span><b>Watch exercise demo</b><small>Renaissance Periodization · ${demo.seconds?demo.seconds+' seconds':'up to 45-second segment'}</small></span></summary><template><iframe src="${url}" title="${esc(demo.name)} — Renaissance Periodization demonstration" loading="lazy" allow="encrypted-media; picture-in-picture; fullscreen" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></template><div class="rp-player-slot"></div><p class="muted">Follow your prescribed range and coach instructions.</p></details><h4>How to do it</h4><ol>${demo.cues.map(cue=>`<li>${esc(cue)}</li>`).join('')}</ol></section>`;
}
const exerciseCardBeforeDemos=exerciseCard;
exerciseCard=function(exercise,loggable=false){
 const demo=rpDemoForExercise(exercise);
 let html=exerciseCardBeforeDemos(exercise,loggable);
 if(!demo)return html.replace('<span class="pill">NO VIDEO</span>','<span class="pill">Demo not yet added</span>');
 html=html.replace(/<a class="btn ghost small"[^>]*>Watch video<\/a>|<span class="pill">NO VIDEO<\/span>/,'<span class="pill">RP technique demo</span>');
 return html.replace('<div class="prescription-grid">',rpDemoMarkup(demo)+'<div class="prescription-grid">');
};
// The sample's shoulder press is explicitly seated to match the demonstration.
const sampleBeforeDemos=fullCoachingSample;
fullCoachingSample=function(index=0){
 const data=sampleBeforeDemos(index);
 for(const exercise of data.exercises||[])if(exercise.name==='Dumbbell shoulder press')exercise.name='Seated dumbbell shoulder press';
 return data;
};
if(typeof exerciseBankMarkup==='function'){
 const bankBeforeDemos=exerciseBankMarkup;
 exerciseBankMarkup=function(){
  const exercises=(state.data.programs||[]).flatMap(p=>(p.days||[]).flatMap(d=>d.exercises||[]));
  const missing=[...new Set(exercises.filter(e=>!rpDemoForExercise(e)).map(e=>e.name))];
  return bankBeforeDemos()+`<section class="panel"><div class="panel-head"><div><h2>RP technique library · ${rpTechniqueDemos.length} movements</h2><span class="sub">Short demonstrations matched to the exact movement. Your client prescriptions stay unchanged.</span></div></div><label class="field">Find an exercise<input type="search" data-rp-search placeholder="Search presses, rows, leg work…"></label><div class="cw-guidance rp-library">${rpTechniqueDemos.map(d=>`<article data-rp-name="${esc(d.name.toLowerCase())}"><h3>${esc(d.name)}</h3>${rpDemoMarkup(d)}</article>`).join('')}</div>${missing.length?`<details><summary>${missing.length} programme movements still need RP demos</summary><ul>${missing.map(name=>`<li>${esc(name)}</li>`).join('')}</ul></details>`:''}</section>`;
 };
}

document.addEventListener('toggle',event=>{const details=event.target;if(!details.matches?.('details.rp-video'))return;const slot=details.querySelector('.rp-player-slot');if(details.open&&!slot.childElementCount)slot.append(details.querySelector('template').content.cloneNode(true));if(!details.open)slot.replaceChildren();},true);
document.addEventListener('input',event=>{if(!event.target.matches?.('[data-rp-search]'))return;const term=event.target.value.trim().toLowerCase();event.target.closest('.panel').querySelectorAll('[data-rp-name]').forEach(card=>card.hidden=!card.dataset.rpName.includes(term));});
