/* Free report extraction runs in the browser. Weekly summaries never become daily observations. */
const weeklyHealthFields={average_steps:['Average daily steps',0,150000],sleep_hours:['Average sleep (hours)',0,24],resting_heart_rate:['Resting heart rate (bpm)',20,250],weight_kg:['Weight (kg)',20,400],workouts:['Workouts in report',0,35],total_steps:['Total steps in report',0,4650000],active_zone_minutes:['Active zone minutes',0,10080],calories_burned:['Average calories burned (not food intake)',0,15000],distance_km:['Total distance (km)',0,3000]};
function parseWeeklyHealthText(input){
 const text=String(input||'').replace(/\u00a0/g,' ').replace(/,/g,'').replace(/\r/g,'');
 const number='([0-9]+(?:\\.[0-9]+)?)';const get=patterns=>{for(const p of patterns){const m=text.match(new RegExp(p,'i'));if(m)return Number(m[1]);}return null;};
 const average_steps=get(['(?:average|avg\\.?|daily average)\\s*(?:daily\\s*)?steps\\s*[:\\-]?\\s*'+number,'steps\\s*(?:daily\\s*)?(?:average|avg\\.?)\\s*[:\\-]?\\s*'+number,'daily avg\\.?\\s*steps\\s*[:\\-]?\\s*'+number]);
 let sleep_hours=get(['(?:average|avg\\.?)\\s*(?:hours of\\s*)?sleep(?:\\s*(?:duration|hours))?\\s*[:\\-]?\\s*'+number,'sleep\\s*(?:average|avg\\.?)\\s*[:\\-]?\\s*'+number]);
 const duration=text.match(/(?:average|avg\.?)\s*(?:hours of\s*)?sleep\s*[:\-]?\s*(\d+)\s*(?:h|hours?)\s*(\d+)\s*(?:m|min|minutes?)/i);if(duration)sleep_hours=Number(duration[1])+Number(duration[2])/60;
 const resting_heart_rate=get(['(?:resting heart rate|resting hr|rhr)\\s*(?:average|avg\\.?)?\\s*[:\\-]?\\s*'+number]);
 let weight_kg=null;const weight=text.match(/(?:weight|body mass)\s*[:\-]?\s*(\d+(?:\.\d+)?)\s*(kg|lbs?|Ib|pounds?)\b/i);if(weight)weight_kg=Number(weight[1])/(weight[2].toLowerCase()==='kg'?1:2.2046226218);
 const workouts=get(['(?:workouts|sessions completed)\\s*[:\\-]?\\s*'+number]);
 const result={average_steps,sleep_hours,resting_heart_rate,weight_kg,workouts,
 total_steps:get([number+'\\s*total steps','total steps\\s*[:\\-]?\\s*'+number]),
 active_zone_minutes:get([number+'\\s*total active zone minutes','(?:total\\s*)?active zone minutes\\s*[:\\-]?\\s*'+number]),
 calories_burned:get([number+'\\s*(?:avg\\.?|average)\\s*(?:daily\\s*)?calories burned','(?:avg\\.?|average)\\s*(?:daily\\s*)?calories burned\\s*[:\\-]?\\s*'+number]),
 distance_km:null};
 const googleSteps=text.match(/(?:Avg\.?|Average)\s*(\d+(?:\.\d+)?)\s*steps\s*\/\s*day/i);if(googleSteps)result.average_steps=Number(googleSteps[1]);
 const googleSleep=text.match(/(\d+)\s*h\s*(\d+)\s*m\s*(?:avg\.?|average)\s*(?:restful\s*)?sleep/i);if(googleSleep)result.sleep_hours=Number(googleSleep[1])+Number(googleSleep[2])/60;
 const googleHr=text.match(/(\d+(?:\.\d+)?)\s*bpm\s*(?:avg\.?|average)\s*resting heart rate/i);if(googleHr)result.resting_heart_rate=Number(googleHr[1]);
 const googleWeight=text.match(/(\d+(?:\.\d+)?)\s*(kg|lbs?|pounds?)\s*(?:avg\.?|average)\s*weight/i);if(googleWeight)result.weight_kg=Number(googleWeight[1])/(googleWeight[2].toLowerCase()==='kg'?1:2.2046226218);
 const distance=text.match(/(\d+(?:\.\d+)?)\s*total\s*(miles|kilometres|kilometers|km)\b/i)||text.match(/total distance\s*[:\-]?\s*(\d+(?:\.\d+)?)\s*(miles|kilometres|kilometers|km)\b/i);if(distance)result.distance_km=Number(distance[1])*(distance[2].toLowerCase()==='miles'?1.609344:1);
 let structured;try{const data=JSON.parse(String(input));structured=data.weekly||data.summary||data.metrics||data;}catch{const lines=String(input).trim().split(/\n/);if(lines.length===2){const headers=lines[0].split(',').map(s=>s.trim().toLowerCase()),values=lines[1].split(',');structured=Object.fromEntries(headers.map((h,i)=>[h,values[i]?.trim()]));}}
 if(structured&&!Array.isArray(structured)&&typeof structured==='object'){for(const key of Object.keys(result)){const value=structured[key]??structured[({average_steps:'average_daily_steps',sleep_hours:'average_sleep_hours',resting_heart_rate:'resting_hr'})[key]];if(value!==undefined&&value!==null&&String(value).trim()!==''&&Number.isFinite(Number(value)))result[key]=Number(value);}if(structured.weight_lb!==undefined&&structured.weight_lb!==null&&String(structured.weight_lb).trim()!=='')result.weight_kg=Number(structured.weight_lb)/2.2046226218;}
 for(const [k,v]of Object.entries(result)){const [,min,max]=weeklyHealthFields[k];if(v!==null&&(!Number.isFinite(v)||v<min||v>max||(k==='workouts'&&!Number.isInteger(v))))result[k]=null;}return result;
}

/* Decode only text MIME parts locally. Never render email HTML or load its remote images. */
function weeklyEmailText(raw){
 const input=String(raw).replace(/\r\n/g,'\n');
 const walk=(part,depth=0)=>{
  if(depth>8)return [];
  const split=part.indexOf('\n\n');if(split<0)return [];
  const headers=part.slice(0,split).replace(/\n[ \t]+/g,' '),body=part.slice(split+2),type=(headers.match(/^Content-Type:\s*([^;\n]+)/im)?.[1]||'text/plain').toLowerCase(),encoding=headers.match(/^Content-Transfer-Encoding:\s*([^\n]+)/im)?.[1].trim().toLowerCase();
  if(type.startsWith('multipart/')){const boundary=headers.match(/boundary\s*=\s*(?:"([^"]+)"|([^;\s]+))/i);if(!boundary)return [];return body.split('--'+(boundary[1]||boundary[2])).slice(1).filter(p=>!p.startsWith('--')).flatMap(p=>walk(p.replace(/^\n/,''),depth+1));}
  if(!['text/plain','text/html'].includes(type)||/Content-Disposition:\s*attachment/i.test(headers))return [];
  let value=body;
  if(encoding==='base64'){try{value=new TextDecoder().decode(Uint8Array.from(atob(body.replace(/\s/g,'')),c=>c.charCodeAt(0)));}catch{throw Error('Could not decode this email. Paste its visible summary instead.');}}
  if(encoding==='quoted-printable'){const bytes=body.replace(/=\n/g,'').replace(/=([a-f0-9]{2})/gi,(_,hex)=>String.fromCharCode(parseInt(hex,16)));value=new TextDecoder().decode(Uint8Array.from(bytes,c=>c.charCodeAt(0)));}

  return [{type,value}];
 };
 const parts=walk(input),chosen=parts.find(p=>p.type==='text/plain')||parts.find(p=>p.type==='text/html');if(!chosen)throw Error('No readable summary was found in this email. Paste its visible text.');
 if(chosen.type==='text/html'){const doc=new DOMParser().parseFromString(chosen.value.replace(/<(script|style|iframe|object|embed)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<(?:img|iframe|object|embed|link|script)\b[^>]*>/gi,''),'text/html');doc.querySelectorAll('script,style,iframe,img').forEach(n=>n.remove());doc.querySelectorAll('br').forEach(n=>n.replaceWith(doc.createTextNode('\n')));doc.querySelectorAll('div,p,tr,td,li').forEach(n=>n.append(doc.createTextNode('\n')));chosen.value=doc.body.textContent;}
 /* Remove tracking URLs and reply headers; retain the report date context. */
 const date=input.match(/^Date:\s*([^\n]+)/im)?.[1];
 return (date?'Email date: '+date+'\n':'')+chosen.value.replace(/https?:\/\/[^\s<>]+/g,'').replace(/^.*(?:From:|To:|Reply-To:).*$/gm,'').trim();
}
function weeklyReportPeriod(text){
 const s=String(text),months=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
 const match=s.match(/stats for\s+([A-Za-z]+)\s+(\d{1,2})(?:,?\s+(20\d{2}))?\s*[-–—]\s*(?:([A-Za-z]+)\s+)?(\d{1,2})(?:,?\s+(20\d{2}))?/i);if(!match)return null;
 const context=s.match(/(?:Email date:|^Date:)\s*[^\n]*\b(20\d{2})\b/im),year=Number(match[6]||match[3]||context?.[1]);if(!year)return null;
 const m1=months.indexOf(match[1].slice(0,3).toLowerCase()),m2=months.indexOf((match[4]||match[1]).slice(0,3).toLowerCase());if(m1<0||m2<0)return null;
 const date=(y,m,d)=>{const dt=new Date(Date.UTC(y,m,Number(d)));return dt.getUTCMonth()===m&&dt.getUTCDate()===Number(d)?dt.toISOString().slice(0,10):null;};
 const end=date(year,m2,match[5]),start=date(m1>m2?year-1:year,m1,match[2]);if(!start||!end||start>end||(Date.parse(end)-Date.parse(start))/864e5>31)return null;return {period_start:start,period_end:end};
}

function weeklyReadTimeout(promise,ms=60000){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error("Reading took too long. Paste the report text or enter its figures, then review and save.")),ms);})]).finally(()=>clearTimeout(timer));}
let weeklyOcrLoader;
async function weeklyOcr(file,status){
 if(!window.Tesseract){weeklyOcrLoader??=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>{weeklyOcrLoader=null;s.remove();reject(Error('Could not load the free reader. Paste the report text or enter its figures below.'));};document.head.append(s);});try{await weeklyReadTimeout(weeklyOcrLoader,30000);}catch(e){weeklyOcrLoader=null;throw e;}}
 let cancelled=false;const workerPromise=window.Tesseract.createWorker('eng',1,{workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/worker.min.js',logger:m=>{if(!cancelled&&status.isConnected&&m.status==='recognizing text')status.textContent='Reading report '+Math.round(m.progress*100)+'%…';}});let worker;try{worker=await weeklyReadTimeout(workerPromise);return (await weeklyReadTimeout(worker.recognize(file))).data.text;}finally{cancelled=true;if(worker)await worker.terminate();else workerPromise.then(w=>w.terminate()).catch(()=>{});}
}
async function weeklyReportText(file,status){
 if(file.size>10*1024*1024)throw Error('Reports must be under 10 MB.');
 if(/^image\/(jpeg|png|webp)$/.test(file.type))return weeklyOcr(file,status);
 if(file.type==='application/pdf'||/\.pdf$/i.test(file.name)){
  const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@6.4.299/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@6.4.299/build/pdf.worker.mjs';
  const task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false});let pdf;
  try{pdf=await task.promise;if(pdf.numPages>12)throw Error('Upload a weekly report of 12 pages or fewer.');let text='';for(let n=1;n<=pdf.numPages;n++){if(status.isConnected)status.textContent='Reading page '+n+' of '+pdf.numPages+'…';const p=await pdf.getPage(n),content=await p.getTextContent();let page=content.items.map(i=>i.str+(i.hasEOL?'\n':' ')).join('');if(page.trim().length<15){const viewport=p.getViewport({scale:1.2}),canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await p.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const blob=await new Promise(resolve=>canvas.toBlob(resolve));page=await weeklyOcr(blob,status);canvas.width=canvas.height=0;}text+=page+'\n';p.cleanup();}return text;}finally{await task.destroy();}
 }
 if(/\.eml$/i.test(file.name)||file.type==='message/rfc822')return weeklyEmailText(await file.text());
 if(/\.(txt|csv|json)$/i.test(file.name))return file.text();throw Error('Use a screenshot, PDF, email (.eml), text, CSV or JSON report.');
}
function weeklyReports(){return (state.data.files||[]).filter(f=>f.file_type==='health_weekly_report').map(f=>{try{const data=JSON.parse(f.notes);return data.version===1?{file:f,...data}:null;}catch{return null;}}).filter(Boolean);}
function weeklyReportCard(r){
 const shown=Object.entries(weeklyHealthFields).filter(([k])=>r.metrics?.[k]!==null&&r.metrics?.[k]!==undefined);
 return `<article class="free-report-card"><div><strong>${esc(r.provider)} · ${esc(fmt(r.period_start))} to ${esc(fmt(r.period_end))}</strong><small>Client-reviewed report · weekly summary, separate from daily device readings</small></div><div class="free-report-values">${shown.map(([k,[label]])=>`<div><span>${esc(label)}</span><b>${Number(r.metrics[k]).toLocaleString(undefined,{maximumFractionDigits:1})}</b></div>`).join('')||'<p>Original report attached. No figures recorded yet.</p>'}</div>${r.file.storage_path?`<button type="button" class="btn ghost small" data-weekly-report-file="${esc(r.file.id)}">Open original report</button>`:''}</article>`;
}
function mountWeeklyReport(host,week=state.checkinWeek||iso(monday())){
 const client=state.client;if(!client||!host)return;const owner=state.preview||state.user?.id===client.profile_id;if(!owner)return;
 const id='weeklyReportForm';host.insertAdjacentHTML('beforeend',`<section class="panel free-report-panel"><span class="eyebrow">FREE · OPTIONAL HEALTH REPORT</span><h3>Your watch or phone summary</h3><p>Upload a weekly screenshot, PDF or saved email (.eml), or paste the summary email. Apple users can upload screenshots of their weekly Health summaries. We read the figures on this device; check them before saving. No exporter subscription.</p><form id="${id}" class="editor-grid"><label>Device<select name="provider"><option>Google / Fitbit</option><option>Apple Health / Apple Watch</option><option>Garmin</option><option>Other wearable</option></select></label><label>Check-in week<input type="date" name="checkin_week" value="${esc(week)}" required></label><label>Report begins<input type="date" name="period_start" value="${esc(week)}" required></label><label>Report ends<input type="date" name="period_end" value="${esc(iso(new Date()))}" required></label><label class="wide">Screenshot or report<input type="file" name="report" accept="image/jpeg,image/png,image/webp,application/pdf,message/rfc822,.eml,.txt,.csv,.json"></label><label class="wide">Or paste your weekly summary<textarea name="report_text" rows="4" maxlength="20000" placeholder="Average daily steps: 8,200&#10;Average sleep: 7h 30m&#10;Resting heart rate: 58 bpm"></textarea></label><button class="btn ghost" type="button" data-read-report>Read figures</button><p class="wide" data-report-status role="status"></p>${Object.entries(weeklyHealthFields).map(([k,[label,min,max]])=>`<label>${label}<input name="${k}" type="number" min="${min}" max="${max}" step="${['average_steps','workouts','total_steps','active_zone_minutes'].includes(k)?'1':'0.1'}" placeholder="Not provided"></label>`).join('')}<label class="wide free-report-consent"><input name="reviewed" type="checkbox" required> This is my report. I checked its dates and figures and want to share this summary with my coach.</label><button class="btn primary" type="submit">Save report for this week</button></form><div data-saved-report></div></section>`);
 const form=host.querySelector('#'+id),status=form.querySelector('[data-report-status]');let reading=0;form.elements.report.onchange=()=>{reading++;form.elements.reviewed.checked=false;form.elements.report_text.value='';for(const k of Object.keys(weeklyHealthFields))form.elements[k].value='';status.textContent='Report selected. Read its figures or enter them manually.';setBusy(form.querySelector('[data-read-report]'),false);};form.addEventListener('input',e=>{if(e.target.name!=='reviewed')form.elements.reviewed.checked=false;});
 form.querySelector('[data-read-report]').onclick=async event=>{const button=event.currentTarget,request=++reading;setBusy(button,true,'Reading…');status.textContent='Reading your report on this device…';try{const file=form.elements.report.files[0],text=file?await weeklyReadTimeout(weeklyReportText(file,status),90000):form.elements.report_text.value;if(!form.isConnected||state.client?.id!==client.id||request!==reading)return;form.elements.report_text.value=String(text).slice(0,20000);const data=parseWeeklyHealthText(text),period=weeklyReportPeriod(text);if(period){form.elements.period_start.value=period.period_start;form.elements.period_end.value=period.period_end;}if(/Google Health|active zone minutes/i.test(text))form.elements.provider.value='Google / Fitbit';for(const [key,value]of Object.entries(data))form.elements[key].value=value===null?'':String(Math.round(value*10)/10);form.elements.reviewed.checked=false;status.textContent=Object.values(data).some(v=>v!==null)?'Figures found. Check each value and the report dates, then save.'+(period&&period.period_end<week?' This report is from an earlier period; confirm the check-in week before saving.':''):'No labelled weekly averages found. Enter the figures you can verify; leave unknown values blank.';}catch(e){if(form.isConnected)status.textContent=e.message;}finally{setBusy(button,false);}};
 form.onsubmit=async event=>{event.preventDefault();const fd=new FormData(form),metrics={};for(const [k,[label,min,max]]of Object.entries(weeklyHealthFields)){const v=fd.get(k);metrics[k]=v===''?null:Number(v);if(v!==''&&(!Number.isFinite(metrics[k])||metrics[k]<min||metrics[k]>max||(['average_steps','workouts','total_steps','active_zone_minutes'].includes(k)&&!Number.isInteger(metrics[k]))))return toast('Check '+label.toLowerCase()+'.','error');}
  const start=String(fd.get('period_start')),end=String(fd.get('period_end')),checkin=String(fd.get('checkin_week')),today=iso(new Date());if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||start>end||end>today||(new Date(end+'T12:00:00')-new Date(start+'T12:00:00'))/864e5>31||!/^\d{4}-\d{2}-\d{2}$/.test(checkin)||new Date(checkin+'T12:00:00').getDay()!==1||checkin>iso(monday()))return toast('Check the report dates and choose a current or past Monday for the check-in week.','error');
  const file=form.elements.report.files[0],text=String(fd.get('report_text')||'').slice(0,20000);if(!file&&!text&&!Object.values(metrics).some(v=>v!==null))return toast('Attach a report or enter its verified figures.','error');if(!fd.has('reviewed'))return toast('Review the report before saving.','error');
  const uploaderId=state.user?.id,data={version:1,provider:fd.get('provider'),checkin_week:checkin,period_start:start,period_end:end,metrics,report_text:text,reviewed_at:new Date().toISOString()},path=file&&/^image\/(jpeg|png|webp)$|^application\/pdf$/.test(file.type)?`${client.id}/${crypto.randomUUID()}-weekly-${file.name.replace(/[^a-z0-9._-]/gi,'-')}`:'';setBusy(event.submitter,true);let uploaded=false;
  try{if(file&&file.size>10*1024*1024)throw Error('Reports must be under 10 MB.');let saved;if(state.preview)saved={id:'sample-report-'+Date.now(),client_id:client.id,file_type:'health_weekly_report',storage_path:'',notes:JSON.stringify(data),created_at:new Date().toISOString()};else{if(path){const {error}=await db.storage.from('client-files').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;uploaded=true;}const rows=await query('Save weekly health report',db.from('client_files').insert({client_id:client.id,uploaded_by:uploaderId,file_type:'health_weekly_report',storage_path:path,original_name:file?.name||'Weekly health summary',mime_type:path?file.type:'text/plain',notes:JSON.stringify(data)}).select());if(rows.length!==1)throw Error('Report save was not confirmed.');saved=rows[0];}
   if(state.client?.id===client.id){state.data.files.unshift(saved);if(form.isConnected){form.parentElement.querySelector('[data-saved-report]').innerHTML=weeklyReportCard({file:saved,...data});status.textContent=state.preview?'Example report saved locally.':'Saved. Your coach can see this report.';setBusy(event.submitter,false);event.submitter.disabled=true;form.addEventListener('input',()=>{event.submitter.disabled=false;},{once:true});const checkinForm=$('#checkinForm');if(checkinForm&&checkin===checkinForm.elements.period_start?.value){if(metrics.sleep_hours!==null&&checkinForm.elements.sleep_hours)checkinForm.elements.sleep_hours.value=metrics.sleep_hours;if(metrics.average_steps!==null&&checkinForm.elements.average_steps)checkinForm.elements.average_steps.value=metrics.average_steps;}}}toast('Weekly report saved');
  }catch(e){if(uploaded)await db.storage.from('client-files').remove([path]);toast(e.message,'error');setBusy(event.submitter,false);}
 };
}
const freeCheckin=clientCheckin;
clientCheckin=function(){freeCheckin();const host=$('#clientMain');mountWeeklyReport(host);if(host.querySelector('#weeklyReportForm')){host.insertAdjacentHTML('afterbegin','<button type="button" class="btn ghost" data-weekly-report-jump>Add watch summary · free</button>');host.querySelector('[data-weekly-report-jump]').onclick=()=>host.querySelector('.free-report-panel').scrollIntoView({behavior:'smooth',block:'start'});}};
const freeHealthSummary=healthSummaryMarkup;
healthSummaryMarkup=function(){const reports=weeklyReports().slice(0,3);return freeHealthSummary()+(reports.length?'<section class="panel"><h3>Weekly watch & phone reports</h3>'+reports.map(weeklyReportCard).join('')+'</section>':'');};
document.addEventListener('click',async event=>{const b=event.target.closest('[data-weekly-report-file]');if(!b)return;const f=state.data.files.find(f=>f.id===b.dataset.weeklyReportFile);if(!f)return;setBusy(b,true);try{const {data,error}=await db.storage.from('client-files').createSignedUrl(f.storage_path,300);if(error)throw error;const a=document.createElement('a');a.href=data.signedUrl;a.target='_blank';a.rel='noopener noreferrer';a.textContent='View original report';b.replaceWith(a);a.click();}catch(e){toast(e.message,'error');setBusy(b,false);}});
const freeCoachCheckins=coachCheckins;
coachCheckins=function(){freeCoachCheckins();const reports=weeklyReports();if(reports.length){const host=$('#clientWorkspaceBody');if(host)host.insertAdjacentHTML('beforeend','<section class="panel"><span class="eyebrow">PRIVATE CLIENT REPORTS</span><h3>Watch reports attached to check-ins</h3>'+reports.map(r=>'<p>Check-in week '+esc(fmt(r.checkin_week))+'</p>'+weeklyReportCard(r)).join('')+'</section>');}};
/* Keep free reports and expose the optional automatic exporter route separately. */
const guidedExporterConnection=openPhoneConnection;
openPhoneConnection=function(target,options){
 phoneFlowDispose?.();let stopped=false,receiptTimer=null,receiptBusy=false;phoneFlowDispose=()=>{stopped=true;clearInterval(receiptTimer);};
 target.innerHTML=`<section class="phone-flow"><header><div><span class="eyebrow">IPHONE & APPLE WATCH</span><h2>Choose how to share</h2></div><button type="button" class="hub-close" data-free-close aria-label="Close phone setup">✕</button></header><p>No subscription is required for weekly reports or Apple Shortcuts. A weekly report is a manual upload. Shortcuts can send readings on a schedule after you build and test it on your iPhone; it is not a ready-installed connection.</p><details><summary>Already have Health Auto Export Premium?</summary><p>This optional route requires the exporter’s paid automation feature. Installing the app alone does not enable it. You do not need to buy it to use Legal Edge.</p><button class="btn ghost" data-auto-exporter>Use my existing exporter automation</button></details><button class="btn primary" data-free-report>Upload a weekly report</button><details data-shortcuts-guide><summary>Set up free Apple Shortcuts sharing</summary><p>This is a setup guide, not a ready-installed shortcut. It needs a first run on your iPhone before use with clients. Reading Health data may fail while the phone is locked.</p><ol><li>In Shortcuts, create “Legal Edge health sharing”. Use Find Health Samples for the readings you approve.</li><li>For steps, use one device/source and the previous complete day. Never sum overlapping phone and watch data. Compare the first total with Health before enabling automatic sharing.</li><li>Use the local date formatted yyyy-MM-dd. Build a Dictionary with a daily list containing date and the selected daily totals. Sleep must be asleep minutes, excluding awake/in-bed and overlapping sleep stages. Missing readings must be omitted.</li><li>Use Get Contents of URL with POST and JSON, and add the private header shown below.</li><li>Run once while unlocked. Only a successful receipt below proves sharing. Then add a Time of Day personal automation with Run Immediately, plus an App Opened trigger as an unlocked catch-up. The first permissions must be approved on your phone.</li></ol><p>For a smooth one-button setup across clients, we still need a tested native phone companion. No direct connection is claimed by this guide.</p><form data-free-key><label><input name="scope" type="checkbox" value="steps" checked> Steps</label><label><input name="scope" type="checkbox" value="sleep_minutes"> Sleep</label><label><input name="scope" type="checkbox" value="weight_kg"> Weight</label><label><input name="scope" type="checkbox" value="resting_heart_rate"> Resting heart rate</label><button class="btn ghost" ${options.owner&&phonePlatform()==='ios'?'':'disabled'}>Prepare my private setup</button></form><div data-free-key-output></div><p data-free-receipt role="status"></p></details><p>Garmin users can share the supported readings Garmin writes to Apple Health, or upload their Garmin report. Android and Google/Fitbit users can upload reports or dated exports; direct automatic account sharing is not active.</p></section>`;
 if(options.preview){const note=document.createElement('section');note.className='journey-note';note.innerHTML='<strong>Sample account · uploads disabled</strong><p>Preview clicks do not connect your phone or save readings.</p><a class="btn primary" href="/?setup=health">Sign in to my real account</a>';target.querySelector('.phone-flow').prepend(note);}
 target.querySelector('[data-auto-exporter]').onclick=()=>guidedExporterConnection(target,options);
 const platform=phonePlatform();
 if(platform!=='ios'){
  const handoff=document.createElement('section');handoff.className='phone-device-handoff';
  const heading=document.createElement('strong');heading.textContent=platform==='android'?'Automatic Android sharing is not available yet':'Continue on your iPhone';
  const note=document.createElement('p');note.textContent=platform==='android'?'You can upload your weekly report. Automatic Health Connect sharing requires an installed Android companion.':'Open this link in Safari on your iPhone and sign in with your own Legal Edge account. Choose the free Shortcuts guide or a weekly report. Run your setup once to confirm an upload.';
  handoff.append(heading,note);
  if(platform==='desktop'){
   const link=document.createElement('a');link.className='phone-safe-link';link.href=phoneSetupUrl(Boolean(options.preview));link.textContent=link.href;
   const copy=document.createElement('button');copy.type='button';copy.className='btn ghost';copy.textContent='Copy iPhone setup link';
   const status=document.createElement('span');status.setAttribute('role','status');
   copy.onclick=async()=>{try{await navigator.clipboard.writeText(link.href);if(!stopped)status.textContent='Link copied';}catch{if(!stopped)status.textContent='Select and copy the link above.';}};
   handoff.append(link,copy,status);
  }
  target.querySelector('[data-free-report]').after(handoff);
 }
 const receipt=document.createElement('section');receipt.className='phone-receipt';receipt.setAttribute('role','status');receipt.textContent=options.preview?'Sample account: no phone data can arrive here.':'No confirmed upload for this setup yet.';target.querySelector('.phone-flow').append(receipt);
 function watchReceipt(id){
  clearInterval(receiptTimer);
  const poll=async()=>{if(stopped||!options.isActive()||!target.isConnected){clearInterval(receiptTimer);return;}if(receiptBusy)return;receiptBusy=true;try{const key=await options.readKey(id);if(stopped||!options.isActive())return;if(key.revoked_at||Date.parse(key.expires_at)<=Date.now()){receipt.textContent='This setup has expired or been disconnected.';clearInterval(receiptTimer);return;}receipt.textContent=key.last_received_at?'Upload received · '+hubStamp(key.last_received_at):'Waiting for the first upload. Run your phone setup once; this screen checks automatically.';if(key.last_received_at)await options.refreshData?.();}catch{if(!stopped)receipt.textContent='Unable to check upload status. Retrying automatically.';}finally{receiptBusy=false;}};
  if(!options.preview&&options.owner){poll();receiptTimer=setInterval(poll,15000);}
 }
 const existingKeys=(options.keys||[]).filter(k=>k.provider==='apple_health'&&!k.revoked_at&&Date.parse(k.expires_at)>Date.now());
 if(options.owner&&existingKeys.length&&!options.preview)watchReceipt((existingKeys.find(k=>k.last_received_at)||existingKeys[0]).id);
 if(options.owner&&existingKeys.length){const panel=document.createElement('section');panel.className='weekly-report';panel.innerHTML='<h3>Existing phone setups</h3><p>Disconnect an old exporter here. Saved readings remain available.</p>';for(const key of existingKeys){const row=document.createElement('div');const label=document.createElement('p');label.textContent=key.last_received_at?'Last upload '+hubStamp(key.last_received_at):'No upload received yet';const button=document.createElement('button');button.type='button';button.className='btn ghost small';button.textContent='Disconnect this setup';button.onclick=async()=>{setBusy(button,true);try{await options.revokeConnection(key.id);if(stopped||!options.isActive())return;row.replaceChildren(document.createTextNode('Setup disconnected.'));}catch(error){toast(error.message,'error');setBusy(button,false);}};row.append(label,button);panel.append(row);}target.querySelector('.phone-flow').append(panel);}
 target.querySelector('[data-free-close]').onclick=()=>{stopped=true;clearInterval(receiptTimer);target.replaceChildren();};target.querySelector('[data-free-report]').onclick=()=>{if(!state.client)return toast('Weekly reports are available inside a client’s check-in.','error');state.clientView='checkin';renderClient();};
 target.querySelector('[data-free-key]').onsubmit=async event=>{event.preventDefault();if(stopped||!options.isActive()||!options.owner||options.preview||phonePlatform()!=='ios')return;const scopes=new FormData(event.target).getAll('scope');if(!scopes.length)return toast('Choose the readings you want to share.','error');setBusy(event.submitter,true);try{const c=await options.createConnection(scopes);if(stopped||!options.isActive())return;watchReceipt(c.id);const host=target.querySelector('[data-free-key-output]');host.innerHTML='<p>Your key is private to this device. Do not share this shortcut publicly or send the key to your coach.</p>';for(const [label,value]of [['Endpoint','https://baxvhilvrhshlfizakak.supabase.co/functions/v1/health-device-ingest'],['Header name','X-Legal-Edge-Key'],['Private header value',c.token]]){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.readOnly=true;i.type=label.includes('Private')?'password':'text';i.value=value;i.autocomplete='off';const b=document.createElement('button');b.type='button';b.className='btn ghost small';b.textContent='Copy '+label.toLowerCase();b.onclick=async()=>{try{await navigator.clipboard.writeText(value);b.textContent='Copied';}catch{toast('Copy failed. Select the value on your phone.','error');}};l.append(i,b);host.append(l);}host.insertAdjacentHTML('beforeend','<p>The JSON request body is a daily list of actual readings. Example shape only: daily → one dictionary → date, steps. Do not upload example numbers.</p><button type="button" class="btn ghost" data-free-recheck>Check first upload</button><button type="button" class="btn ghost" data-free-revoke>Disconnect setup</button>');host.querySelector('[data-free-recheck]').onclick=async()=>{try{const row=await options.readKey(c.id);target.querySelector('[data-free-receipt]').textContent=row.last_received_at?'Data received '+hubStamp(row.last_received_at):'No upload received yet. The phone is not connected.';}catch(e){toast(e.message,'error');}};host.querySelector('[data-free-revoke]').onclick=async()=>{try{await options.revokeConnection(c.id);clearInterval(receiptTimer);receipt.textContent='Setup disconnected.';host.replaceChildren();target.querySelector('[data-free-receipt]').textContent='Setup disconnected.';}catch(e){toast(e.message,'error');}};}catch(e){toast(e.message,'error');}finally{setBusy(event.submitter,false);}};
};
hubProviders.find(p=>p.id==='apple_health').route='Free reports & Shortcuts · optional exporter';hubProviders.find(p=>p.id==='apple_health').description='Share a free weekly report or build an Apple Shortcuts automation. An existing paid exporter is optional.';
