/* Free report extraction runs in the browser. Weekly summaries never become daily observations. */
const weeklyHealthFields={average_steps:['Average daily steps',0,150000],sleep_hours:['Average sleep (hours)',0,24],resting_heart_rate:['Resting heart rate (bpm)',20,250],weight_kg:['Weight (kg)',20,400],workouts:['Workouts in report',0,35]};
function parseWeeklyHealthText(input){
 const text=String(input||'').replace(/\u00a0/g,' ').replace(/,/g,'').replace(/\r/g,'');
 const number='([0-9]+(?:\\.[0-9]+)?)';const get=patterns=>{for(const p of patterns){const m=text.match(new RegExp(p,'i'));if(m)return Number(m[1]);}return null;};
 const average_steps=get(['(?:average|avg\\.?|daily average)\\s*(?:daily\\s*)?steps\\s*[:\\-]?\\s*'+number,'steps\\s*(?:daily\\s*)?(?:average|avg\\.?)\\s*[:\\-]?\\s*'+number,'daily avg\\.?\\s*steps\\s*[:\\-]?\\s*'+number]);
 let sleep_hours=get(['(?:average|avg\\.?)\\s*(?:hours of\\s*)?sleep(?:\\s*(?:duration|hours))?\\s*[:\\-]?\\s*'+number,'sleep\\s*(?:average|avg\\.?)\\s*[:\\-]?\\s*'+number]);
 const duration=text.match(/(?:average|avg\.?)\s*(?:hours of\s*)?sleep\s*[:\-]?\s*(\d+)\s*(?:h|hours?)\s*(\d+)\s*(?:m|min|minutes?)/i);if(duration)sleep_hours=Number(duration[1])+Number(duration[2])/60;
 const resting_heart_rate=get(['(?:resting heart rate|resting hr|rhr)\\s*(?:average|avg\\.?)?\\s*[:\\-]?\\s*'+number]);
 let weight_kg=null;const weight=text.match(/(?:weight|body mass)\s*[:\-]?\s*(\d+(?:\.\d+)?)\s*(kg|lbs?|pounds?)\b/i);if(weight)weight_kg=Number(weight[1])/(weight[2].toLowerCase()==='kg'?1:2.2046226218);
 const workouts=get(['(?:workouts|sessions completed)\\s*[:\\-]?\\s*'+number]);
 const result={average_steps,sleep_hours,resting_heart_rate,weight_kg,workouts};
 let structured;try{const data=JSON.parse(String(input));structured=data.weekly||data.summary||data.metrics||data;}catch{const lines=String(input).trim().split(/\n/);if(lines.length===2){const headers=lines[0].split(',').map(s=>s.trim().toLowerCase()),values=lines[1].split(',');structured=Object.fromEntries(headers.map((h,i)=>[h,values[i]?.trim()]));}}
 if(structured&&!Array.isArray(structured)&&typeof structured==='object'){for(const key of Object.keys(result)){const value=structured[key]??structured[({average_steps:'average_daily_steps',sleep_hours:'average_sleep_hours',resting_heart_rate:'resting_hr'})[key]];if(value!==undefined&&value!==null&&String(value).trim()!==''&&Number.isFinite(Number(value)))result[key]=Number(value);}if(structured.weight_lb!==undefined&&structured.weight_lb!==null&&String(structured.weight_lb).trim()!=='')result.weight_kg=Number(structured.weight_lb)/2.2046226218;}
 for(const [k,v]of Object.entries(result)){const [,min,max]=weeklyHealthFields[k];if(v!==null&&(!Number.isFinite(v)||v<min||v>max||(k==='workouts'&&!Number.isInteger(v))))result[k]=null;}return result;
}
let weeklyOcrLoader;
async function weeklyOcr(file,status){
 if(!window.Tesseract){weeklyOcrLoader??=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>{weeklyOcrLoader=null;s.remove();reject(Error('Could not load the free reader. Paste the report text or enter its figures below.'));};document.head.append(s);});await weeklyOcrLoader;}
 const worker=await window.Tesseract.createWorker('eng',1,{workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/worker.min.js',logger:m=>{if(status.isConnected&&m.status==='recognizing text')status.textContent='Reading report '+Math.round(m.progress*100)+'%…';}});
 try{return (await worker.recognize(file)).data.text;}finally{await worker.terminate();}
}
async function weeklyReportText(file,status){
 if(file.size>10*1024*1024)throw Error('Reports must be under 10 MB.');
 if(/^image\/(jpeg|png|webp)$/.test(file.type))return weeklyOcr(file,status);
 if(file.type==='application/pdf'||/\.pdf$/i.test(file.name)){
  const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@6.4.299/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@6.4.299/build/pdf.worker.mjs';
  const task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false});let pdf;
  try{pdf=await task.promise;if(pdf.numPages>12)throw Error('Upload a weekly report of 12 pages or fewer.');let text='';for(let n=1;n<=pdf.numPages;n++){if(status.isConnected)status.textContent='Reading page '+n+' of '+pdf.numPages+'…';const p=await pdf.getPage(n),content=await p.getTextContent();let page=content.items.map(i=>i.str+(i.hasEOL?'\n':' ')).join('');if(page.trim().length<15){const viewport=p.getViewport({scale:1.2}),canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await p.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const blob=await new Promise(resolve=>canvas.toBlob(resolve));page=await weeklyOcr(blob,status);canvas.width=canvas.height=0;}text+=page+'\n';p.cleanup();}return text;}finally{if(pdf)await pdf.destroy();else await task.destroy();}
 }
 if(/\.(txt|csv|json)$/i.test(file.name))return file.text();throw Error('Use a screenshot, PDF, text, CSV or JSON report.');
}
function weeklyReports(){return (state.data.files||[]).filter(f=>f.file_type==='health_weekly_report').map(f=>{try{const data=JSON.parse(f.notes);return data.version===1?{file:f,...data}:null;}catch{return null;}}).filter(Boolean);}
function weeklyReportCard(r){
 const shown=Object.entries(weeklyHealthFields).filter(([k])=>r.metrics?.[k]!==null&&r.metrics?.[k]!==undefined);
 return `<article class="free-report-card"><div><strong>${esc(r.provider)} · ${esc(fmt(r.period_start))} to ${esc(fmt(r.period_end))}</strong><small>Client-reviewed report · weekly summary, separate from daily device readings</small></div><div class="free-report-values">${shown.map(([k,[label]])=>`<div><span>${esc(label)}</span><b>${Number(r.metrics[k]).toLocaleString(undefined,{maximumFractionDigits:1})}</b></div>`).join('')||'<p>Original report attached. No figures recorded yet.</p>'}</div>${r.file.storage_path?`<button type="button" class="btn ghost small" data-weekly-report-file="${esc(r.file.id)}">Open original report</button>`:''}</article>`;
}
function mountWeeklyReport(host,week=state.checkinWeek||iso(monday())){
 const client=state.client;if(!client||!host)return;const owner=state.preview||state.user?.id===client.profile_id;if(!owner)return;
 const id='weeklyReportForm';host.insertAdjacentHTML('beforeend',`<section class="panel free-report-panel"><span class="eyebrow">FREE · OPTIONAL HEALTH REPORT</span><h3>Your watch or phone summary</h3><p>Upload a weekly screenshot or PDF, or paste the summary email. We read the figures on this device; check them before saving. No exporter subscription.</p><form id="${id}" class="editor-grid"><label>Device<select name="provider"><option>Google / Fitbit</option><option>Apple Health / Apple Watch</option><option>Garmin</option><option>Other wearable</option></select></label><label>Check-in week<input type="date" name="checkin_week" value="${esc(week)}" required></label><label>Report begins<input type="date" name="period_start" value="${esc(week)}" required></label><label>Report ends<input type="date" name="period_end" value="${esc(iso(new Date()))}" required></label><label class="wide">Screenshot or report<input type="file" name="report" accept="image/jpeg,image/png,image/webp,application/pdf,.txt,.csv,.json"></label><label class="wide">Or paste your weekly summary<textarea name="report_text" rows="4" maxlength="20000" placeholder="Average daily steps: 8,200&#10;Average sleep: 7h 30m&#10;Resting heart rate: 58 bpm"></textarea></label><button class="btn ghost" type="button" data-read-report>Read figures</button><p class="wide" data-report-status role="status"></p>${Object.entries(weeklyHealthFields).map(([k,[label,min,max]])=>`<label>${label}<input name="${k}" type="number" min="${min}" max="${max}" step="${k==='average_steps'||k==='workouts'?'1':'0.1'}" placeholder="Not provided"></label>`).join('')}<label class="wide free-report-consent"><input name="reviewed" type="checkbox" required> I checked the dates and figures against my report and want to share this summary with my coach.</label><button class="btn primary" type="submit">Save report for this week</button></form><div data-saved-report></div></section>`);
 const form=host.querySelector('#'+id),status=form.querySelector('[data-report-status]');let reading=0;
 form.querySelector('[data-read-report]').onclick=async event=>{const request=++reading;setBusy(event.currentTarget,true,'Reading…');status.textContent='Reading your report on this device…';try{const file=form.elements.report.files[0],text=file?await weeklyReportText(file,status):form.elements.report_text.value;if(!form.isConnected||state.client?.id!==client.id||request!==reading)return;form.elements.report_text.value=String(text).slice(0,20000);const data=parseWeeklyHealthText(text);for(const [key,value]of Object.entries(data))form.elements[key].value=value===null?'':String(Math.round(value*10)/10);form.elements.reviewed.checked=false;status.textContent=Object.values(data).some(v=>v!==null)?'Figures found. Check each value and the report dates, then save.':'No labelled weekly averages found. Enter the figures you can verify; leave unknown values blank.';}catch(e){if(form.isConnected)status.textContent=e.message;}finally{setBusy(event.currentTarget,false);}};
 form.onsubmit=async event=>{event.preventDefault();const fd=new FormData(form),metrics={};for(const [k,[label,min,max]]of Object.entries(weeklyHealthFields)){const v=fd.get(k);metrics[k]=v===''?null:Number(v);if(v!==''&&(!Number.isFinite(metrics[k])||metrics[k]<min||metrics[k]>max||(['average_steps','workouts'].includes(k)&&!Number.isInteger(metrics[k]))))return toast('Check '+label.toLowerCase()+'.','error');}
  const start=String(fd.get('period_start')),end=String(fd.get('period_end')),checkin=String(fd.get('checkin_week')),today=iso(new Date());if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||start>end||end>today||(new Date(end+'T12:00:00')-new Date(start+'T12:00:00'))/864e5>31||!/^\d{4}-\d{2}-\d{2}$/.test(checkin)||new Date(checkin+'T12:00:00').getDay()!==1||checkin>iso(monday()))return toast('Check the report dates and choose a current or past Monday for the check-in week.','error');
  const file=form.elements.report.files[0],text=String(fd.get('report_text')||'').slice(0,20000);if(!file&&!text&&!Object.values(metrics).some(v=>v!==null))return toast('Attach a report or enter its verified figures.','error');if(!fd.has('reviewed'))return toast('Review the report before saving.','error');
  const uploaderId=state.user?.id,data={version:1,provider:fd.get('provider'),checkin_week:checkin,period_start:start,period_end:end,metrics,report_text:text,reviewed_at:new Date().toISOString()},path=file&&/^image\/(jpeg|png|webp)$|^application\/pdf$/.test(file.type)?`${client.id}/${crypto.randomUUID()}-weekly-${file.name.replace(/[^a-z0-9._-]/gi,'-')}`:'';setBusy(event.submitter,true);let uploaded=false;
  try{if(file&&file.size>10*1024*1024)throw Error('Reports must be under 10 MB.');let saved;if(state.preview)saved={id:'sample-report-'+Date.now(),client_id:client.id,file_type:'health_weekly_report',storage_path:'',notes:JSON.stringify(data),created_at:new Date().toISOString()};else{if(path){const {error}=await db.storage.from('client-files').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;uploaded=true;}const rows=await query('Save weekly health report',db.from('client_files').insert({client_id:client.id,uploaded_by:uploaderId,file_type:'health_weekly_report',storage_path:path,original_name:file?.name||'Weekly health summary',mime_type:path?file.type:'text/plain',notes:JSON.stringify(data)}).select());if(rows.length!==1)throw Error('Report save was not confirmed.');saved=rows[0];}
   if(state.client?.id===client.id){state.data.files.unshift(saved);if(form.isConnected){form.parentElement.querySelector('[data-saved-report]').innerHTML=weeklyReportCard({file:saved,...data});status.textContent=state.preview?'Example report saved locally.':'Saved. Your coach can see this report.';setBusy(event.submitter,false);event.submitter.disabled=true;form.addEventListener('input',()=>{event.submitter.disabled=false;},{once:true});const checkinForm=$('#checkinForm');if(checkinForm&&checkin===checkinForm.elements.period_start?.value){if(metrics.sleep_hours!==null&&checkinForm.elements.sleep_hours)checkinForm.elements.sleep_hours.value=metrics.sleep_hours;if(metrics.average_steps!==null&&checkinForm.elements.average_steps)checkinForm.elements.average_steps.value=metrics.average_steps;}}}toast('Weekly report saved');
  }catch(e){if(uploaded)await db.storage.from('client-files').remove([path]);toast(e.message,'error');setBusy(event.submitter,false);}
 };
}
const freeCheckin=clientCheckin;
clientCheckin=function(){freeCheckin();const host=$('#clientMain');mountWeeklyReport(host);if(host.querySelector('#weeklyReportForm')){host.insertAdjacentHTML('afterbegin','<button type="button" class="btn ghost" data-weekly-report-jump>Add watch summary · free</button>');host.querySelector('[data-weekly-report-jump]').onclick=()=>host.querySelector('.free-report-panel').scrollIntoView({behavior:'smooth',block:'start'});}};
const freeHealthSummary=healthSummaryMarkup;
healthSummaryMarkup=function(){const reports=weeklyReports().slice(0,3);return freeHealthSummary()+(reports.length?'<section class="panel"><h3>Weekly watch & phone reports</h3>'+reports.map(weeklyReportCard).join('')+'</section>':'');};
document.addEventListener('click',async event=>{const b=event.target.closest('[data-weekly-report-file]');if(!b)return;const f=state.data.files.find(f=>f.id===b.dataset.weeklyReportFile);if(!f)return;setBusy(b,true);try{const {data,error}=await db.storage.from('client-files').createSignedUrl(f.storage_path,300);if(error)throw error;const a=document.createElement('a');a.href=data.signedUrl;a.target='_blank';a.rel='noopener noreferrer';a.textContent='View original report';b.replaceWith(a);a.click();}catch(e){toast(e.message,'error');setBusy(b,false);}});
/* Replace the paid-app requirement with free exports and an explicitly untested personal automation guide. */
openPhoneConnection=function(target,options){
 phoneFlowDispose?.();let stopped=false;phoneFlowDispose=()=>{stopped=true;};
 target.innerHTML=`<section class="phone-flow"><header><div><span class="eyebrow">NO EXPORTER SUBSCRIPTION</span><h2>Free iPhone sharing</h2></div><button type="button" class="hub-close" data-free-close aria-label="Close phone setup">✕</button></header><p>Apple Health cannot connect directly to a website. You can upload a free report now, or build a personal automation with Apple's included Shortcuts app.</p><button class="btn primary" data-free-report>Upload a weekly report</button><details><summary>Free Apple Shortcuts automation · advanced setup</summary><p>This is a setup guide, not a ready-installed shortcut. It needs a first run on your iPhone before use with clients. Reading Health data may fail while the phone is locked.</p><ol><li>In Shortcuts, create “Legal Edge health sharing”. Use Find Health Samples for the readings you approve.</li><li>For steps, use one device/source and the previous complete day. Never sum overlapping phone and watch data. Compare the first total with Health before enabling automatic sharing.</li><li>Use the local date formatted yyyy-MM-dd. Build a Dictionary with a daily list containing date and the selected daily totals. Sleep must be asleep minutes, excluding awake/in-bed and overlapping sleep stages. Missing readings must be omitted.</li><li>Use Get Contents of URL with POST and JSON, and add the private header shown below.</li><li>Run once while unlocked. Only a successful receipt below proves sharing. Then add a Time of Day personal automation with Run Immediately, plus an App Opened trigger as an unlocked catch-up. The first permissions must be approved on your phone.</li></ol><p>For a smooth one-button setup across clients, we still need a tested native phone companion. No direct connection is claimed by this guide.</p><form data-free-key><label><input name="scope" type="checkbox" value="steps" checked> Steps</label><label><input name="scope" type="checkbox" value="sleep_minutes"> Sleep</label><label><input name="scope" type="checkbox" value="weight_kg"> Weight</label><label><input name="scope" type="checkbox" value="resting_heart_rate"> Resting heart rate</label><button class="btn ghost" ${options.owner&&phonePlatform()==='ios'?'':'disabled'}>Prepare my private setup</button></form><div data-free-key-output></div><p data-free-receipt role="status"></p></details><p>Garmin users can share the supported readings Garmin writes to Apple Health, or upload their Garmin report. Android and Google/Fitbit users can upload reports or dated exports; direct automatic account sharing is not active.</p></section>`;
 target.querySelector('[data-free-close]').onclick=()=>{stopped=true;target.replaceChildren();};target.querySelector('[data-free-report]').onclick=()=>{if(!state.client)return toast('Weekly reports are available inside a client’s check-in.','error');state.clientView='checkin';renderClient();};
 target.querySelector('[data-free-key]').onsubmit=async event=>{event.preventDefault();const scopes=new FormData(event.target).getAll('scope');if(!scopes.length)return toast('Choose the readings you want to share.','error');setBusy(event.submitter,true);try{const c=await options.createConnection(scopes);if(stopped||!options.isActive())return;const host=target.querySelector('[data-free-key-output]');host.innerHTML='<p>Your key is private to this device. Do not share this shortcut publicly or send the key to your coach.</p>';for(const [label,value]of [['Endpoint','https://baxvhilvrhshlfizakak.supabase.co/functions/v1/health-device-ingest'],['Header name','X-Legal-Edge-Key'],['Private header value',c.token]]){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.readOnly=true;i.type=label.includes('Private')?'password':'text';i.value=value;i.autocomplete='off';const b=document.createElement('button');b.type='button';b.className='btn ghost small';b.textContent='Copy '+label.toLowerCase();b.onclick=async()=>{try{await navigator.clipboard.writeText(value);b.textContent='Copied';}catch{toast('Copy failed. Select the value on your phone.','error');}};l.append(i,b);host.append(l);}host.insertAdjacentHTML('beforeend','<p>The JSON request body is a daily list of actual readings. Example shape only: daily → one dictionary → date, steps. Do not upload example numbers.</p><button type="button" class="btn ghost" data-free-recheck>Check first upload</button><button type="button" class="btn ghost" data-free-revoke>Disconnect setup</button>');host.querySelector('[data-free-recheck]').onclick=async()=>{try{const row=await options.readKey(c.id);target.querySelector('[data-free-receipt]').textContent=row.last_received_at?'Data received '+hubStamp(row.last_received_at):'No upload received yet. The phone is not connected.';}catch(e){toast(e.message,'error');}};host.querySelector('[data-free-revoke]').onclick=async()=>{try{await options.revokeConnection(c.id);host.replaceChildren();target.querySelector('[data-free-receipt]').textContent='Setup disconnected.';}catch(e){toast(e.message,'error');}};}catch(e){toast(e.message,'error');}finally{setBusy(event.submitter,false);}};
};
hubProviders.find(p=>p.id==='apple_health').route='Free reports & Apple Shortcuts guide';hubProviders.find(p=>p.id==='apple_health').description='Share a weekly report or export for free. Shortcuts automation needs setup on your iPhone.';
