// Hevy reads happen server-side. Never retain or display an API key after submit.
let hevyRefreshTimer=null,hevyViewRequest=0;
function hevyHistoryMarkup(rows,unit='kg'){return rows.length?rows.map(w=>`<details class="panel"><summary>${esc(w.title)} · ${esc(fmt(w.start_time.slice(0,10)))}</summary>${w.exercises.map(e=>`<h3>${esc(e.title)}</h3><div class="note-row">${e.sets.map((s,i)=>`<span>Set ${i+1}: ${s.weight_kg==null?'':(Number(s.weight_kg)*(unit==='lbs'?2.2046226218:1)).toFixed(1)+' '+(unit==='lbs'?'lb':'kg')+' · '}${s.reps==null?'':s.reps+' reps'}${s.duration_seconds==null?'':' · '+s.duration_seconds+' sec'}${s.distance_meters==null?'':' · '+s.distance_meters+' m'}${s.type==='warmup'?' · warm-up':''}</span>`).join('')}</div>${e.notes?`<p>${esc(e.notes)}</p>`:''}`).join('')}</details>`).join(''):'<p>No Hevy workouts imported yet.</p>';}
async function mountHevyConnection(target,own,clientId=null,unit='kg'){
 clearInterval(hevyRefreshTimer);const request=++hevyViewRequest,section=document.createElement('section');section.className='panel';section.id='hevyConnection';
 section.innerHTML=`<span class="eyebrow">HEVY WORKOUT SYNC</span><h2>Connect Hevy</h2><p>Bring completed workouts, recorded sets, reps and weights into your private coaching history. Requires Hevy Pro. Your prescribed Legal Edge programme stays separate.</p>${own?`<form id="hevyConnectForm"><label>Hevy API key<input name="api_key" type="password" required autocomplete="off" spellcheck="false"></label><button class="btn primary">Connect and import workouts</button></form>`:'<p class="muted">Only the signed-in account owner can connect their Hevy account. This preview does not make real connections.</p>'}<p><a href="https://hevy.com/settings?developer" target="_blank" rel="noopener">Get your API key in Hevy Pro settings ↗</a></p><p class="muted">Paste the key here, not in chat. It is encrypted on the backend and is never included in client or employer reports. This integration reads Hevy; it does not change workouts or routines there.</p><div id="hevyStatus" aria-live="polite">${own?'Checking connection…':'Not connected in this preview.'}</div><div id="hevyHistory"></div>`;target.append(section);if(new URLSearchParams(location.search).get('setup')==='hevy')section.scrollIntoView({block:'start'});
 if(!own&&!clientId)return;
 let selectedClient=clientId,connected=false,busy=false;
 const valid=()=>request===hevyViewRequest&&section.isConnected;
 async function load(){if(!selectedClient){const rows=await query('My Hevy profile',db.from('clients').select('id').eq('profile_id',state.user.id).limit(1));selectedClient=rows[0]?.id;}if(!valid())return;if(!selectedClient){$('#hevyStatus').textContent='Ready to connect. No key saved yet.';return;}const [connections,workouts]=await Promise.all([own?query('Hevy connection',db.from('hevy_connections').select('client_id,status,last_synced_at').eq('client_id',selectedClient)):Promise.resolve([]),query('Hevy workout history',db.from('hevy_workouts').select('hevy_id,title,start_time,exercises').eq('client_id',selectedClient).order('start_time',{ascending:false}).limit(10))]);if(!valid())return;const connection=connections[0];connected=connection?.status==='connected';$('#hevyStatus').innerHTML=own?`<p>${connected?'Connected · Last import '+esc(new Date(connection.last_synced_at).toLocaleString()):connection?.status==='needs_reconnect'?'Hevy needs a new valid key.':'Not connected'}</p>${connected?'<button type="button" class="btn ghost" id="hevySyncNow">Sync now</button> ':''}${connection&&connection.status!=='disconnected'?'<button type="button" class="btn ghost" id="hevyDisconnect">Disconnect Hevy</button>':''}<p class="muted">Imports up to your latest 100 workouts; shows the latest 10 here. Imports daily in the background and refreshes while this page is open. Imported records remain after disconnecting. Hevy deletions are not mirrored.</p>`:'<p>Imported Hevy history · connection managed privately by this client.</p>';$('#hevyHistory').innerHTML=hevyHistoryMarkup(workouts,unit);$('#hevySyncNow')?.addEventListener('click',()=>invoke('sync'));$('#hevyDisconnect')?.addEventListener('click',()=>invoke('disconnect'));}
 async function invoke(action,apiKey){if(!own||busy||!valid())return;busy=true;try{const {data,error}=await db.functions.invoke('hevy-sync',{body:{action,...(apiKey?{api_key:apiKey}:{})}});if(error||data?.error){let message=data?.error;try{if(!message&&error?.context)message=(await error.context.json()).error;}catch{}throw Error(message||'Hevy request failed. Check your key and Pro subscription.');}await load();if(valid())toast(action==='disconnect'?'Hevy disconnected':data.recent?'Already up to date':`${data.imported||0} Hevy workouts imported`);}catch(error){if(valid())toast(error.message,'error');}finally{busy=false;}}
 $('#hevyConnectForm')?.addEventListener('submit',async e=>{e.preventDefault();const key=e.target.elements.api_key.value.trim();e.target.reset();await invoke('connect',key);});
 await load();if(own)hevyRefreshTimer=setInterval(()=>{if(!valid()){clearInterval(hevyRefreshTimer);return;}if(connected&&!document.hidden)invoke('sync');},120000);
}
const hevyCoachHealthBefore=renderCoachHealth;
renderCoachHealth=async function(){await hevyCoachHealthBefore();if(state.coachView==='my-health'&&$('#coachMain'))await mountHevyConnection($('#coachMain'),!state.preview&&state.role==='coach'&&state.user?.id===state.profile?.id);};
const hevyClientHealthBefore=clientHealth;
clientHealth=function(){hevyClientHealthBefore();mountHevyConnection($('#clientMain'),!state.preview&&state.user?.id===state.client?.profile_id,state.preview?null:state.client?.id,state.client?.weight_unit||'kg').catch(e=>toast(e.message,'error'));};
async function appendHevyTraining(target){if(state.preview||!state.client?.id)return;const clientId=state.client.id,section=document.createElement('section');section.className='panel';target.append(section);try{const rows=await query('Imported Hevy workouts',db.from('hevy_workouts').select('hevy_id,title,start_time,exercises').eq('client_id',clientId).order('start_time',{ascending:false}).limit(10));if(!section.isConnected||state.client?.id!==clientId)return;if(!rows.length){section.remove();return;}section.innerHTML='<span class="eyebrow">RECORDED IN HEVY</span><h2>Imported workout history</h2><p>Actual logged workouts. These do not automatically tick off a prescribed session.</p>'+hevyHistoryMarkup(rows,state.client.weight_unit||'kg');}catch{section.remove();}}
const hevyTrainingBefore=clientTraining;clientTraining=function(){hevyTrainingBefore();appendHevyTraining($('#clientMain'));};
const hevyCoachTrainingBefore=coachTraining;coachTraining=function(){hevyCoachTrainingBefore();appendHevyTraining($('#coachMain'));};
