export function hevyWorkoutRows(payload,clientId){
 if(!Array.isArray(payload?.workouts)||payload.workouts.length>10)throw Error('Invalid Hevy workout response');
 const number=v=>typeof v==='number'&&Number.isFinite(v)?v:null;
 const date=v=>typeof v==='string'&&Number.isFinite(Date.parse(v))?new Date(v).toISOString():null;
 return payload.workouts.map(w=>{const start=date(w.start_time);if(typeof w.id!=='string'||!w.id.length||w.id.length>100||!start||!Array.isArray(w.exercises)||w.exercises.length>100)throw Error('Invalid Hevy workout');return {client_id:clientId,hevy_id:w.id,title:String(w.title||'Hevy workout').slice(0,300),start_time:start,end_time:date(w.end_time),source_updated_at:date(w.updated_at),exercises:w.exercises.map(e=>{if(!Array.isArray(e.sets)||e.sets.length>100)throw Error('Invalid Hevy sets');return {title:String(e.title||'Exercise').slice(0,300),exercise_template_id:String(e.exercise_template_id||'').slice(0,100),notes:String(e.notes||'').slice(0,2000),sets:e.sets.map(s=>({type:String(s.type||'normal').slice(0,20),weight_kg:number(s.weight_kg),reps:number(s.reps),distance_meters:number(s.distance_meters),duration_seconds:number(s.duration_seconds),rpe:number(s.rpe)}))};}),synced_at:new Date().toISOString()};});
}
export async function credentialKey(secret){const input=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'HKDF',false,['deriveKey']);return crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt:new TextEncoder().encode('Legal Edge Hevy v1'),info:new TextEncoder().encode('credential encryption')},input,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
const encode=a=>btoa(String.fromCharCode(...new Uint8Array(a))),decode=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export async function sealKey(value,secret,clientId){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await credentialKey(secret),bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(clientId)},key,new TextEncoder().encode(value));return {key_ciphertext:encode(bytes),key_iv:encode(iv)};}
export async function openKey(row,secret,clientId){const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(row.key_iv),additionalData:new TextEncoder().encode(clientId)},await credentialKey(secret),decode(row.key_ciphertext));return new TextDecoder().decode(bytes);}
