import {createClient} from 'jsr:@supabase/supabase-js@2.57.4';
import {hevyWorkoutRows,sealKey,openKey} from './model.mjs';
const headers={'Access-Control-Allow-Origin':'https://legal-edge-client-app.vercel.app','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json','Cache-Control':'no-store'};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
async function page(key:string,page:number){const r=await fetch('https://api.hevyapp.com/v1/workouts?page='+page+'&pageSize=10',{headers:{'api-key':key,Accept:'application/json'},signal:AbortSignal.timeout(12000),redirect:'error'});if(!r.ok)throw Error(r.status===401||r.status===403?'HEVY_KEY':r.status===429?'HEVY_RATE':'HEVY_UNAVAILABLE');const text=await r.text();if(text.length>2e6)throw Error('HEVY_UNAVAILABLE');return JSON.parse(text);}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return reply({error:'POST required'},405);
 const authorization=req.headers.get('authorization')||'',url=Deno.env.get('SUPABASE_URL')!,secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const admin=createClient(url,secret,{auth:{persistSession:false}}),caller=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:authorization}},auth:{persistSession:false}});
 const {data:{user},error:authError}=await caller.auth.getUser();if(authError||!user)return reply({error:'Sign in required'},401);
 let client:any,action:string='';
 try{
  if(Number(req.headers.get('content-length')||0)>4096)return reply({error:'Request too large'},413);const raw=await req.text();if(raw.length>4096)return reply({error:'Request too large'},413);const body=JSON.parse(raw);action=body.action;if(!['connect','sync','disconnect'].includes(action)||body.client_id)return reply({error:'Invalid connection request'},400);
  const found=await admin.from('clients').select('id,profile_id').eq('profile_id',user.id).maybeSingle();if(found.error)throw found.error;client=found.data;
  if(!client&&action==='connect'){const {data:profile,error}=await admin.from('profiles').select('role,full_name').eq('id',user.id).single();if(error||profile.role!=='coach')return reply({error:'Your saved client record needs a linked login first'},403);const created=await admin.from('clients').insert({profile_id:user.id,coach_id:user.id,display_name:profile.full_name||'My personal health',email:user.email,source_system:'coach_health_test',source_id:user.id,weekly_checkin_enabled:false,track_weight:false,portal_enabled:false}).select('id,profile_id').single();if(created.error?.code==='23505')client=(await admin.from('clients').select('id,profile_id').eq('profile_id',user.id).single()).data;else if(created.error)throw created.error;else client=created.data;}
  if(!client||client.profile_id!==user.id)return reply({error:'Your own linked health record is required'},403);
  if(action==='disconnect'){const {error}=await admin.from('hevy_connections').update({status:'disconnected',key_ciphertext:null,key_iv:null,updated_at:new Date().toISOString()}).eq('client_id',client.id);if(error)throw error;return reply({disconnected:true});}
  let apiKey:string,connection:any;
  if(action==='connect'){apiKey=String(body.api_key||'').trim();if(!/^[a-zA-Z0-9_-]{20,200}$/.test(apiKey))return reply({error:'Enter your Hevy API key from Hevy Pro settings'},400);}
  else {const stored=await admin.from('hevy_connections').select('*').eq('client_id',client.id).single();connection=stored.data;if(stored.error||!connection?.key_ciphertext||connection.status==='disconnected')return reply({error:'Connect your Hevy Pro account first'},400);if(connection.last_synced_at&&Date.now()-Date.parse(connection.last_synced_at)<60000)return reply({synced:true,recent:true,last_synced_at:connection.last_synced_at});try{apiKey=await openKey(connection,secret,client.id);}catch{return reply({error:'Reconnect Hevy after credential rotation'},409);}}
  const first=await page(apiKey,1),rows=hevyWorkoutRows(first,client.id),pageCount=Number(first.page_count);if(!Number.isInteger(pageCount)||pageCount<0||pageCount>100000)throw Error('HEVY_UNAVAILABLE');
  for(let i=2;i<=Math.min(pageCount,10);i++){const next=await page(apiKey,i);rows.push(...hevyWorkoutRows(next,client.id));}
  const unique=[...new Map(rows.map(r=>[r.hevy_id,r])).values()];if(unique.length){const {error}=await admin.from('hevy_workouts').upsert(unique,{onConflict:'client_id,hevy_id'});if(error)throw error;}
  const stamp=new Date().toISOString(),sealed=action==='connect'?await sealKey(apiKey,secret,client.id):{};
  const saved=action==='connect'?await admin.from('hevy_connections').upsert({client_id:client.id,...sealed,status:'connected',last_synced_at:stamp,updated_at:stamp}):await admin.from('hevy_connections').update({status:'connected',last_synced_at:stamp,updated_at:stamp}).eq('client_id',client.id).eq('key_ciphertext',connection.key_ciphertext).neq('status','disconnected').select('client_id');if(saved.error)throw saved.error;if(action==='sync'&&!saved.data?.length)return reply({error:'Connection changed during sync; reconnect if needed'},409);
  return reply({synced:true,imported:unique.length,last_synced_at:stamp,history_limit:100,more_history:pageCount>10});
 }catch(error){const reason=error instanceof Error?error.message:'';if(reason==='HEVY_KEY'&&client&&action==='sync')await admin.from('hevy_connections').update({status:'needs_reconnect',updated_at:new Date().toISOString()}).eq('client_id',client.id);return reply({error:reason==='HEVY_KEY'?'Hevy rejected the key. Check your Pro subscription and API key.':reason==='HEVY_RATE'?'Hevy rate limit reached. Try again later.':'Hevy sync could not complete. Your existing plans are preserved.'},reason==='HEVY_KEY'?400:reason==='HEVY_RATE'?429:502);}
});
