const fs=require('fs'),vm=require('vm'),assert=require('assert');
const app=fs.readFileSync(__dirname+'/../app-v2.js','utf8').split('\nbindShell();')[0];
const document={addEventListener(){},getElementById(){return null;}};
const ctx=vm.createContext({window:{supabase:null,addEventListener(){}},document,location:{hash:'',search:''},URLSearchParams,URL,console,Date,Set,Map,setTimeout,clearTimeout,setInterval,clearInterval});
vm.runInContext(app+'\n'+fs.readFileSync(__dirname+'/../plan-experience.js','utf8'),ctx);
vm.runInContext('function exerciseTrackingMode(ex){return ex.tracking_type||"reps";}\nfunction integrityShopping(){}\n'+fs.readFileSync(__dirname+'/../daily-tools.js','utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
run(`state.client={id:'own',weight_unit:'kg'};state.user={id:'coach'};state.foodUnits='metric';state.data=emptyData();state.data.mealAssignments=[{nutrition_plan_id:'p',meal:{name:'Meal',ingredients:[{name:'Chicken (raw)',quantity:100,unit:'g'},{name:'Chicken (raw)',quantity:0.1,unit:'kg'},{name:'Chicken (cooked)',quantity:100,unit:'g'},{name:'Salt',quantity:0.3,unit:'g'},{name:'Milk',quantity:100,unit:'ml'},{name:'Milk',quantity:0.1,unit:'l'},{name:'Missing food',quantity:null,unit:'g'},{name:'Invalid food',quantity:-1,unit:'g'}]}}];var days=[{date:'2026-10-05',plan:{id:'p'}},{date:'2026-10-06',plan:{id:'p'}}];`);
assert.equal(run("weeklyShoppingData(days).items.find(i=>i.name==='Chicken (raw)').quantity"),400);
assert.equal(run("weeklyShoppingData(days).items.find(i=>i.name==='Chicken (cooked)').quantity"),200);
assert.equal(run("weeklyShoppingData(days).items.find(i=>i.name==='Salt').quantity"),0.6);
assert.equal(run("weeklyShoppingData(days).items.find(i=>i.name==='Milk').quantity"),400);
assert.equal(run('weeklyShoppingData(days).missing.length'),2);
assert.match(run('shoppingListMarkup(days)'),/Missing food|Invalid food/);
assert.match(run('shoppingListMarkup(days)'),/0.6 g/);
const original=run('shoppingDownloadText(weeklyShoppingData(days))');run('state.mealBatchPortions=7');assert.equal(run('shoppingDownloadText(weeklyShoppingData(days))'),original);
run("weeklyShoppingData(days).checks.selected.add(weeklyShoppingData(days).items[0].key)");assert.equal(run('weeklyShoppingData(days).checks.selected.size'),1);
run("state.client.id='other'");assert.equal(run('weeklyShoppingData(days).checks.selected.size'),0);
run("state.client.id='own'");assert.equal(run('weeklyShoppingData(days).checks.selected.size'),1);
run("days[0].date='2026-10-12'");assert.equal(run('weeklyShoppingData(days).checks.selected.size'),0);
run("days[0].date='2026-10-05';state.data.mealAssignments[0].meal.ingredients[0].quantity=105");assert.equal(run('weeklyShoppingData(days).checks.selected.size'),0);
assert.equal(run("shoppingAmount({quantity:1,unit:'lb'}).quantity"),453.59237);
assert.equal(run("shoppingAmount({quantity:1,unit:'fl oz'}).unit"),'ml');
assert.match(run("exerciseCard({id:'ex',name:'Bench press',rest_seconds:90},true)"),/Start 1:30 rest/);
assert.doesNotMatch(run("exerciseCard({id:'ex',name:'Mobility',rest_seconds:90,tracking_type:'completion'},true)"),/data-start-rest/);
run('restState.deadline=10000;restState.remaining=90');assert.equal(run('restSecondsRemaining(5100)'),5);assert.equal(run('restSecondsRemaining(15000)'),0);run('restState.deadline=null;restState.remaining=4');assert.equal(run('restSecondsRemaining(50000)'),4);
run("restState.owner=restOwner();state.client.id='new'");assert.notEqual(run('restState.owner'),run('restOwner'));
assert.equal(run('state.data.exerciseLogs.length'),0);
console.log('PASS: weekly food totals, compatible mass/volume conversion, raw/cooked separation, fractional quantities, missing-amount warnings, batch independence, client/week/revision scoped checks, download, elapsed-time rest and no actual workout writes.');
