const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync(__dirname+'/../free-health.js','utf8');
const ctx=vm.createContext({TextDecoder,Uint8Array,atob,openPhoneConnection(){},coachCheckins(){},console,Date,Intl,Map,Set,FormData,JSON,Number,window:{},document:{addEventListener(){}},state:{data:{files:[]}},clientCheckin(){},healthSummaryMarkup(){return ''},hubProviders:[{id:'apple_health'}]});vm.runInContext(code,ctx);
let r=ctx.parseWeeklyHealthText('Average daily steps: 8,200\nAverage sleep: 7h 30m\nResting heart rate: 58 bpm\nWeight: 176 lb\nWorkouts: 3');assert.equal(r.average_steps,8200);assert.equal(r.sleep_hours,7.5);assert.equal(r.resting_heart_rate,58);assert.equal(r.workouts,3);assert(Math.abs(r.weight_kg-79.832)<.01);
r=ctx.parseWeeklyHealthText('Total steps: 52,000\nCalories: 1950\nWeight: 80');assert.equal(r.average_steps,null);assert.equal(r.weight_kg,null);assert.equal(r.sleep_hours,null);
r=ctx.parseWeeklyHealthText('{"summary":{"average_steps":0,"sleep_hours":7.2,"resting_heart_rate":60,"weight_kg":80}}');assert.equal(r.average_steps,0);assert.equal(r.sleep_hours,7.2);assert.equal(r.weight_kg,80);
r=ctx.parseWeeklyHealthText('average_steps,sleep_hours,resting_heart_rate\n8600,7.5,58');assert.equal(r.average_steps,8600);assert.equal(r.sleep_hours,7.5);
r=ctx.parseWeeklyHealthText('Average steps: 999999\nAverage sleep: 450\nResting heart rate: 2\nWorkouts: 3.5');assert(Object.values(r).every(v=>v===null));
assert(!code.includes("from('client_health_daily')"));assert(code.includes("file_type:'health_weekly_report'"));assert(code.includes('createSignedUrl(f.storage_path,300)'));assert(code.includes('client_id:client.id'));assert(code.includes('if(state.client?.id===client.id)'));assert(code.includes('await worker.terminate()'));
console.log('PASS: free weekly report parsing, hours/minutes, explicit units, zero values, JSON/CSV, range checks, weekly averages kept separate and client-bound private report storage.');

const sample='Google Health\nEmail date: Tue, 22 Sep 2026\nHere are your stats for Sep 12 - Sep 18\n56,861\ntotal steps\nAvg 8,123 steps/day\n6h 42m\navg. restful sleep\n62 bpm\navg. resting heart rate\n160lb\navg. weight\n250\ntotal active zone minutes\n2,100\navg. calories burned\n24.5\ntotal miles';
r=ctx.parseWeeklyHealthText(sample);assert.equal(r.average_steps,8123);assert.equal(r.total_steps,56861);assert.equal(r.sleep_hours,6.7);assert.equal(r.resting_heart_rate,62);assert.equal(r.active_zone_minutes,250);assert.equal(r.calories_burned,2100);assert(Math.abs(r.distance_km-39.4289)<.001);assert(Math.abs(r.weight_kg-72.5748)<.001);assert.equal(ctx.weeklyReportPeriod(sample).period_start,'2026-09-12');assert.equal(ctx.weeklyReportPeriod(sample).period_end,'2026-09-18');assert.equal(ctx.weeklyReportPeriod('stats for Sep 12 - Sep 18'),null);assert.equal(ctx.weeklyReportPeriod('stats for Feb 30 - Mar 2, 2026'),null);
const eml='Date: Tue, 22 Sep 2026\nContent-Type: multipart/alternative; boundary="qa"\n\n--qa\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: base64\n\n'+Buffer.from(sample).toString('base64')+'\n--qa--';assert.equal(ctx.parseWeeklyHealthText(ctx.weeklyEmailText(eml)).average_steps,8123);assert.equal(ctx.weeklyReportPeriod(ctx.weeklyEmailText(eml)).period_end,'2026-09-18');
const qp='Content-Type: text/plain\nContent-Transfer-Encoding: quoted-printable\n\nAvg 8,1=\n23 steps/day';assert.equal(ctx.parseWeeklyHealthText(ctx.weeklyEmailText(qp)).average_steps,8123);
assert(code.includes('message/rfc822,.eml'));assert(code.includes('This is my report.'));assert(code.includes('Watch reports attached to check-ins'));console.log('PASS: Google report layout, eight metric types, MIME email decoding, safe dates and no calorie-intake inference.');
