const fs=require('fs'),vm=require('vm'),assert=require('assert');
const noop=()=>{},ctx=vm.createContext({fullCoachingSample:noop,exerciseEditorMarkup:()=>'',programDayBuilderMarkup:()=>'',validateTrainingPlan:p=>p,workoutSetRows:(e,s,fd,c)=>Array.from({length:e.sets},(_,i)=>({set_number:i+1,reps:fd.get('reps_'+(i+1))})).filter(r=>r.reps!==null),exerciseCard:(e)=>'<span>SETS</span><strong>'+e.sets+'</strong><form class="set-log">'+Array.from({length:e.sets},(_,i)=>'<b>Set '+(i+1)+'</b>').join('')+'</form></article>',coachTraining:noop,trainingPrompt:()=>'',clientTraining:noop,renderSharedSampleSponsor:noop,paintFirmPilots:noop,coachOverview:noop,document:{addEventListener:noop},exerciseTrackingMode:()=> 'reps',esc:String,iso:d=>new Date(d).toISOString().slice(0,10),monday:()=>new Date('2026-10-05T12:00:00Z'),fmt:String,state:{data:{exerciseLogs:[]}},Number,Date,Map});vm.runInContext(fs.readFileSync(__dirname+'/../exercise-demos.js','utf8'),ctx);vm.runInContext(fs.readFileSync(__dirname+'/../performance-ready.js','utf8'),ctx);
for(const frequency of [2,3]){const plan=ctx.hypertrophyTemplate(frequency);ctx.validateTrainingPlan(plan);assert.equal(plan.days.length,frequency);assert(plan.days.every(d=>d.exercises.length>=6));for(const day of plan.days)for(const ex of day.exercises)assert(ctx.rpDemoForExercise(ex),'Missing demonstration for '+ex.name);}
assert.throws(()=>ctx.validateTrainingPlan({days:[{title:'Invalid',exercises:[{name:'Press',superset_group:'A',combination_type:'triset'}]}]}),/exactly 3/);
assert.throws(()=>ctx.trainingTechniquePatch({get:k=>k==='drop_sets'?4:null}),/zero to three/);
const ex={id:'ex',sets:3,drop_sets:2},fd={get:k=>({'reps_1':8,'reps_4':12,'reps_5':10}[k]??null)},rows=ctx.workoutSetRows(ex,{id:'s'},fd,{});assert.equal(rows.length,3);assert.equal(rows[1].set_number,4);assert.equal(rows[1].notes,'Drop 1 after working set 3');assert.equal(rows[2].notes,'Drop 2 after working set 3');
const html=ctx.exerciseCard(ex,true);assert(html.includes('Drop 1'));assert(html.includes('Drop 2'));assert(html.includes('<strong>3</strong>'));
const report=ctx.firmTrendMarkup([{week_start:'2026-09-28',enrolled:10,eligible:8,respondents:6,coverage_pct:75,energy:5},{week_start:'2026-10-05',enrolled:10,eligible:8,respondents:8,coverage_pct:100,energy:7}]);assert(report.includes('+2.0 / 10'));assert(report.includes('Withheld')===false);assert(report.includes('Awaiting comparison'));assert(report.includes('matched-person'));
console.log('PASS: complete templates, strict pair sizes, bounded drops, separate actual drop logs, working-set counts, trends and missing metric handling.');
