// Full existing script chain, synthetic backend, no production records or browser session.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),content=JSON.parse(fs.readFileSync(path.join(root,'playbook/content.json')));
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://example.invalid/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
w.HTMLElement.prototype.scrollIntoView=function(){};w.fetch=async()=>({ok:true,json:async()=>content});w.navigator.clipboard={writeText:async()=>{}};
let rejectSave=false,uploads=0,accepted=0;const tables={coaching_start_resources:content.map(r=>({...r,id:r.slug,coach_id:'coach',updated_at:'2026-10-09T00:00:00Z',archived:false})),playbook_workout_options:[],playbook_workout_history:[],playbook_bookmarks:[],playbook_recommendations:[],playbook_feedback:[],playbook_events:[],playbook_collections:[],playbook_collection_assignments:[],playbook_cohort_consents:[]};
const db={auth:{getUser:async()=>({data:{user:null}}),onAuthStateChange(){}},storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:'https://example.invalid/media'},error:null}),upload:async()=>{uploads++;return{data:{},error:null};}})},rpc:async(name,p)=>{if(name==='accept_playbook_workout'){accepted++;const o=tables.playbook_workout_options.find(o=>o.id===p.p_option);tables.playbook_workout_history.unshift({id:'h1',client_id:o.client_id,session_id:o.session_id,adjusted:[{id:'ex1',name:'Assigned squat',sets:1,reps:'6',load:'20'}],original:[{id:'ex1',name:'Assigned squat',sets:3,reps:'6',load:'20'}],active:true,note:'Keep your warm-up'});return{data:'h1'};}if(name==='restore_playbook_workout'){tables.playbook_workout_history[0].active=false;return{data:true};}return{data:[]};},from(table){let filters=[],payload=null,mode=null,single=false,offset=0,end=Infinity;const q={select(){return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},neq(k,v){filters.push(r=>r[k]!==v);return q;},is(k,v){filters.push(r=>(r[k]??null)===v);return q;},not(){return q;},in(k,vs){filters.push(r=>vs.includes(r[k]));return q;},order(){return q;},limit(n){end=n-1;return q;},range(a,b){offset=a;end=b;return q;},textSearch(k,s){filters.push(r=>(r.title+' '+r.quick_answer).toLowerCase().includes(s.toLowerCase()));return q;},single(){single=true;return q;},insert(p){payload=p;mode='insert';return q;},upsert(p){payload=p;mode='upsert';return q;},update(p){payload=p;mode='update';return q;},delete(){mode='delete';return q;},then(resolve,reject){return Promise.resolve().then(()=>{const rows=(tables[table]||=[]);if(payload&&rejectSave)return{data:null,error:{message:'Save rejected'}};if(payload){if(mode==='insert'||mode==='upsert')rows.push({id:payload.id||'new-'+rows.length,...payload});else rows.filter(r=>filters.every(f=>f(r))).forEach(r=>Object.assign(r,payload));}if(mode==='delete')tables[table]=rows.filter(r=>!filters.every(f=>f(r)));const result=(tables[table]||[]).filter(r=>filters.every(f=>f(r))).slice(offset,end+1);return{data:single?result[0]:result,error:null};}).then(resolve,reject);}};return q;}};
w.supabase={createClient:()=>db};const ctx=dom.getInternalVMContext(),run=s=>vm.runInContext(s,ctx),doc=w.document;
for(const s of doc.querySelectorAll('script[src^="./"]')){const file=s.getAttribute('src').slice(2).split('?')[0];vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});}
const tick=()=>new Promise(r=>setTimeout(r,0));async function settle(){for(let i=0;i<8;i++)await tick();}
(async()=>{
 run(`state.role='client';state.preview=false;state.user={id:'owner'};state.client={id:'client',profile_id:'owner',coach_id:'coach',onboarding_status:'complete',plan_status:'published'};state.data=emptyData();state.data.weeks=[{id:'week',published:true,week_start:'2026-10-05'}];state.data.sessions=[{id:'session',week_id:'week',title:'Assigned session',session_date:'2026-10-09',training_type:'weights',status:'planned'}];state.data.exercises=[{id:'ex1',session_id:'session',name:'Assigned squat',sets:3,reps:'6',load:'20'}];state.clientView='playbook';renderClient();`);await settle();
 assert(doc.querySelector('.pb-hero').textContent.includes('What do you need help with today?'));assert.equal(doc.querySelectorAll('[data-pb-problem]').length,6);assert.equal(doc.querySelectorAll('#clientNav [data-client-view="playbook"]').length,1);assert(!doc.querySelector('#clientNav [data-client-view="learning"]'));assert(!doc.querySelectorAll('[data-pb-resource]').length,'Home does not dump the library');
 doc.querySelector('#pbBrowse').click();await settle();assert.equal(doc.querySelectorAll('[data-pb-resource]').length,12);doc.querySelector('[data-pb-resource]').click();await settle();assert(doc.querySelector('.pb-answer'));assert(!doc.querySelector('video'));assert(!doc.querySelector('.pb-detail').open);assert(doc.querySelectorAll('#pbRelated [data-pb-resource]').length<=3);
 doc.querySelector('#pbFeedback [value=yes]').checked=true;doc.querySelector('#pbFeedback textarea').value='Useful, but add a travel example.';rejectSave=true;doc.querySelector('#pbFeedback').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.equal(tables.playbook_feedback.length,0);assert(!doc.querySelector('#pbFeedbackStatus').textContent);rejectSave=false;doc.querySelector('#pbFeedback').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.equal(tables.playbook_feedback[0].client_id,'client');assert(doc.querySelector('#pbFeedbackStatus').textContent.includes('Saved'));
 doc.querySelector('[data-pb-home]').click();await settle();doc.querySelector('[data-pb-tool=workout]').click();await settle();let f=doc.querySelector('#pbWorkout');f.elements.namedItem('energy').value='unwell';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert(doc.querySelector('#pbWorkoutPreview').textContent.includes('Pause'));assert.equal(accepted,0);f.elements.namedItem('energy').value='good';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert(doc.querySelector('#pbWorkoutPreview').textContent.includes('No approved option'));
 tables.playbook_workout_options.push({id:'opt',client_id:'client',session_id:'session',minutes:20,location:'gym',energy:'good',approved:true,exercises:[{id:'ex1',sets:1}],note:'Keep your warm-up'});run(`state.clientView='today';renderClient();state.clientView='playbook';state.client={...state.client,id:'other'};renderClient();`);await settle();assert(!doc.querySelector('#pbWorkoutPreview'),'Client switch clears the previous tool');run(`state.client.id='client';renderClient();`);await settle();doc.querySelector('[data-pb-tool=workout]').click();await settle();f=doc.querySelector('#pbWorkout');f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert(doc.querySelector('#pbAccept'));doc.querySelector('#pbAccept').click();await settle();assert.equal(accepted,1);assert.equal(run('state.data.exercises[0].sets'),3,'Original preserved');assert(doc.querySelector('#pbRestore'));assert.equal(run('exercisesForSession(state.data.sessions[0])[0].sets'),1);doc.querySelector('#pbRestore').click();await settle();assert.equal(run('exercisesForSession(state.data.sessions[0])[0].sets'),3);
 run(`state.client=null;state.role='coach';state.user={id:'coach'};state.clients=[];state.coachView='playbook-manager';renderCoach();`);await settle();assert(doc.querySelector('#pbManagerBody').textContent.includes('12 published'));doc.querySelector('[data-pb-edit]').click();await settle();assert(doc.querySelector('#pbEditorForm'));assert(doc.querySelector('[data-pb-upload=video_path]'));assert(doc.querySelector('[name=video_script]').value.includes('HOOK'));assert(doc.querySelector('[name=slide_outline]').value);assert.equal(uploads,0);
 run(`state.role='client';state.user={id:'new'};state.client={id:'new',coach_id:'coach',onboarding_status:'invited',plan_status:'not_started'};state.clientView='playbook';renderClient();`);await settle();assert(!doc.querySelector('.pb-hero'),'Incomplete intake keeps existing onboarding gate');
 console.log('PASS Playbook DOM: six clean entry choices; one nav; 12 published guides; optional deeper/media; feedback failure/confirmation; illness/no-option protection; approved preview/accept/restore; original preserved; client-switch isolation; coach editor/media/script; onboarding gate.');dom.window.close();
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
