begin;
create temporary table weekly_report_test(coach_id uuid,client_id uuid,profile_id uuid,other_id uuid);
insert into weekly_report_test select id,gen_random_uuid(),gen_random_uuid(),gen_random_uuid() from public.profiles where role='coach' limit 1;
insert into auth.users(id,email,raw_user_meta_data) select profile_id,'weekly-report-qa@example.invalid','{"full_name":"Disposable weekly report QA"}'::jsonb from weekly_report_test;
insert into public.profiles(id,role,full_name,email) select profile_id,'client','Disposable weekly report QA','weekly-report-qa@example.invalid' from weekly_report_test on conflict(id) do nothing;
insert into public.clients(id,coach_id,profile_id,display_name) select client_id,coach_id,profile_id,'Disposable weekly report QA' from weekly_report_test;
grant select on weekly_report_test to authenticated;
select set_config('request.jwt.claim.sub',(select profile_id::text from weekly_report_test),true);
set local role authenticated;
insert into public.client_files(client_id,uploaded_by,file_type,storage_path,original_name,mime_type,notes) select client_id,profile_id,'health_weekly_report','','Disposable report QA','text/plain','{"version":1,"metrics":{"average_steps":8200}}' from weekly_report_test;
do $$ begin if not exists(select 1 from public.client_files where client_id=(select client_id from weekly_report_test) and file_type='health_weekly_report') then raise exception 'TEST FAILED own report read';end if;end $$;
select set_config('request.jwt.claim.sub',(select coach_id::text from weekly_report_test),true);
do $$ begin if not exists(select 1 from public.client_files where client_id=(select client_id from weekly_report_test) and file_type='health_weekly_report') then raise exception 'TEST FAILED assigned coach report read';end if;end $$;
select set_config('request.jwt.claim.sub',(select other_id::text from weekly_report_test),true);
do $$ begin if exists(select 1 from public.client_files where client_id=(select client_id from weekly_report_test)) then raise exception 'TEST FAILED unrelated report read';end if;
begin insert into public.client_files(client_id,file_type,storage_path,notes) select client_id,'health_weekly_report','','{}' from weekly_report_test;raise exception 'TEST FAILED unrelated report insert';exception when insufficient_privilege then null;end;
end $$;
reset role;
do $$ begin if exists(select 1 from public.client_health_daily where client_id=(select client_id from weekly_report_test)) then raise exception 'TEST FAILED weekly average invented daily readings';end if;end $$;
select 'PASS rollback only: owner and assigned coach read weekly report; other account cannot read or write; no fabricated daily readings.' as result;
rollback;
